import {
  LEVEL_THEMES, PLACEMENT_TYPE_CIABATTA,
  PLACEMENT_TYPE_FLOUR, PLACEMENT_TYPE_FLYING_ENEMY,
  PLACEMENT_TYPE_GOAL,
  PLACEMENT_TYPE_HERO,
  PLACEMENT_TYPE_WALL,
  PLACEMENT_TYPE_GROUND_ENEMY,
  PLACEMENT_TYPE_ROAMING_ENEMY,
  PLACEMENT_TYPE_LOCK,
  PLACEMENT_TYPE_KEY,
  PLACEMENT_TYPE_WATER,
  PLACEMENT_TYPE_WATER_PICKUP,
  PLACEMENT_TYPE_THIEF,
  PLACEMENT_TYPE_RABBIT,
  PLACEMENT_TYPE_SWITCH_DOOR,
  PLACEMENT_TYPE_SWITCH,
  PLACEMENT_TYPE_CONVEYOR
} from "../helpers/consts";

const DemoLevel2 = {
  theme: LEVEL_THEMES.GRAY,
  tilesWidth: 15,
  tilesHeight: 12,
  placements: [
    { x: 2, y: 2, type: PLACEMENT_TYPE_HERO },
    { x: 8, y: 2, type: PLACEMENT_TYPE_GOAL },

    { x: 5, y: 1, type: PLACEMENT_TYPE_WATER },
    { x: 5, y: 2, type: PLACEMENT_TYPE_WATER },
    { x: 5, y: 3, type: PLACEMENT_TYPE_WATER },
    { x: 6, y: 1, type: PLACEMENT_TYPE_WATER },
    { x: 6, y: 2, type: PLACEMENT_TYPE_WATER },
    { x: 6, y: 3, type: PLACEMENT_TYPE_WATER },
    { x: 7, y: 1, type: PLACEMENT_TYPE_WATER },
    { x: 7, y: 2, type: PLACEMENT_TYPE_WATER },
    { x: 7, y: 3, type: PLACEMENT_TYPE_WATER },
    { x: 8, y: 1, type: PLACEMENT_TYPE_WATER },
    { x: 8, y: 3, type: PLACEMENT_TYPE_WATER },
    { x: 9, y: 1, type: PLACEMENT_TYPE_WATER },
    { x: 9, y: 2, type: PLACEMENT_TYPE_WATER },
    { x: 9, y: 3, type: PLACEMENT_TYPE_WATER },
    { x: 10, y: 1, type: PLACEMENT_TYPE_WATER },
    { x: 10, y: 2, type: PLACEMENT_TYPE_WATER },
    { x: 10, y: 3, type: PLACEMENT_TYPE_WATER },
    { x: 11, y: 1, type: PLACEMENT_TYPE_WATER },
    { x: 11, y: 2, type: PLACEMENT_TYPE_WATER },
    { x: 11, y: 3, type: PLACEMENT_TYPE_WATER },
    { x: 13, y: 1, type: PLACEMENT_TYPE_WATER },
    { x: 13, y: 2, type: PLACEMENT_TYPE_WATER },
    { x: 13, y: 3, type: PLACEMENT_TYPE_WATER },
    { x: 14, y: 1, type: PLACEMENT_TYPE_WATER },
    { x: 14, y: 3, type: PLACEMENT_TYPE_WATER },
    { x: 15, y: 1, type: PLACEMENT_TYPE_WATER },
    { x: 15, y: 2, type: PLACEMENT_TYPE_WATER },
    { x: 15, y: 3, type: PLACEMENT_TYPE_WATER },

    { x: 3, y: 5, type: PLACEMENT_TYPE_WATER },
    { x: 3, y: 6, type: PLACEMENT_TYPE_WATER },
    { x: 3, y: 7, type: PLACEMENT_TYPE_WATER },
    { x: 3, y: 8, type: PLACEMENT_TYPE_WATER },
    { x: 4, y: 5, type: PLACEMENT_TYPE_WATER },
    { x: 4, y: 6, type: PLACEMENT_TYPE_WATER },
    { x: 4, y: 7, type: PLACEMENT_TYPE_WATER },
    { x: 4, y: 8, type: PLACEMENT_TYPE_WATER },
    { x: 5, y: 5, type: PLACEMENT_TYPE_WATER },
    { x: 5, y: 6, type: PLACEMENT_TYPE_WATER },
    { x: 5, y: 7, type: PLACEMENT_TYPE_WATER },
    { x: 5, y: 8, type: PLACEMENT_TYPE_WATER },
    { x: 6, y: 5, type: PLACEMENT_TYPE_WATER },
    { x: 6, y: 7, type: PLACEMENT_TYPE_WATER },
    { x: 6, y: 8, type: PLACEMENT_TYPE_WATER },
    { x: 7, y: 8, type: PLACEMENT_TYPE_WATER },
    { x: 8, y: 8, type: PLACEMENT_TYPE_WATER },
    { x: 9, y: 8, type: PLACEMENT_TYPE_WATER },
    { x: 10, y: 5, type: PLACEMENT_TYPE_WATER },
    { x: 10, y: 7, type: PLACEMENT_TYPE_WATER },
    { x: 10, y: 8, type: PLACEMENT_TYPE_WATER },
    { x: 11, y: 5, type: PLACEMENT_TYPE_WATER },
    { x: 11, y: 7, type: PLACEMENT_TYPE_WATER },
    { x: 11, y: 8, type: PLACEMENT_TYPE_WATER },
    { x: 12, y: 5, type: PLACEMENT_TYPE_WATER },
    { x: 12, y: 7, type: PLACEMENT_TYPE_WATER },
    { x: 12, y: 8, type: PLACEMENT_TYPE_WATER },
    { x: 13, y: 5, type: PLACEMENT_TYPE_WATER },
    { x: 13, y: 7, type: PLACEMENT_TYPE_WATER },
    { x: 13, y: 8, type: PLACEMENT_TYPE_WATER },
    { x: 14, y: 5, type: PLACEMENT_TYPE_WATER },
    { x: 15, y: 5, type: PLACEMENT_TYPE_WATER },
    { x: 15, y: 6, type: PLACEMENT_TYPE_WATER },
    { x: 15, y: 7, type: PLACEMENT_TYPE_WATER },
    { x: 15, y: 8, type: PLACEMENT_TYPE_WATER },

    { x: 2, y: 7, type: PLACEMENT_TYPE_WATER_PICKUP },

    { x: 1, y: 4, type: PLACEMENT_TYPE_WALL },
    { x: 3, y: 4, type: PLACEMENT_TYPE_WALL },
    { x: 4, y: 1, type: PLACEMENT_TYPE_WALL },
    { x: 4, y: 3, type: PLACEMENT_TYPE_WALL },
    { x: 4, y: 4, type: PLACEMENT_TYPE_WALL },
    { x: 5, y: 4, type: PLACEMENT_TYPE_WALL },
    { x: 6, y: 4, type: PLACEMENT_TYPE_WALL },
    { x: 7, y: 4, type: PLACEMENT_TYPE_WALL },
    { x: 9, y: 4, type: PLACEMENT_TYPE_WALL },
    { x: 10, y: 4, type: PLACEMENT_TYPE_WALL },
    { x: 11, y: 4, type: PLACEMENT_TYPE_WALL },
    { x: 12, y: 1, type: PLACEMENT_TYPE_WALL },
    { x: 12, y: 3, type: PLACEMENT_TYPE_WALL },
    { x: 12, y: 4, type: PLACEMENT_TYPE_WALL },
    { x: 13, y: 4, type: PLACEMENT_TYPE_WALL },
    { x: 15, y: 4, type: PLACEMENT_TYPE_WALL },

    { x: 1, y: 9, type: PLACEMENT_TYPE_WALL },
    { x: 3, y: 9, type: PLACEMENT_TYPE_WALL },
    { x: 4, y: 9, type: PLACEMENT_TYPE_WALL },
    { x: 5, y: 9, type: PLACEMENT_TYPE_WALL },
    { x: 4, y: 10, type: PLACEMENT_TYPE_WALL },
    { x: 4, y: 12, type: PLACEMENT_TYPE_WALL },
    { x: 6, y: 9, type: PLACEMENT_TYPE_WALL },
    { x: 6, y: 11, type: PLACEMENT_TYPE_WALL },
    { x: 7, y: 9, type: PLACEMENT_TYPE_WALL },
    { x: 7, y: 11, type: PLACEMENT_TYPE_WALL },
    { x: 8, y: 9, type: PLACEMENT_TYPE_WALL },
    { x: 10, y: 11, type: PLACEMENT_TYPE_WALL },
    { x: 9, y: 9, type: PLACEMENT_TYPE_WALL },
    { x: 9, y: 11, type: PLACEMENT_TYPE_WALL },
    { x: 10, y: 9, type: PLACEMENT_TYPE_WALL },
    { x: 11, y: 9, type: PLACEMENT_TYPE_WALL },
    { x: 12, y: 10, type: PLACEMENT_TYPE_WALL },
    { x: 12, y: 12, type: PLACEMENT_TYPE_WALL },
    { x: 12, y: 9, type: PLACEMENT_TYPE_WALL },
    { x: 13, y: 9, type: PLACEMENT_TYPE_WALL },
    { x: 15, y: 9, type: PLACEMENT_TYPE_WALL },

    { x: 12, y: 2, type: PLACEMENT_TYPE_LOCK,color:'BLUE' },
    { x: 8, y: 12, type: PLACEMENT_TYPE_KEY,color:'BLUE' },

    { x: 14, y: 4, type: PLACEMENT_TYPE_LOCK,color:'GREEN' },
    { x: 14, y: 11, type: PLACEMENT_TYPE_KEY,color:'GREEN' },

    // { x: 10, y: 6, type: PLACEMENT_TYPE_THIEF },
    // { x: 14, y: 8, type: PLACEMENT_TYPE_THIEF },

    { x: 8, y: 4, type: PLACEMENT_TYPE_RABBIT,Talking:'你知道嗎？月亮的表面可不是軟綿綿的，而是滿滿的石頭和岩石哦！',point:'石頭和岩石'},
    { x: 8, y: 11, type: PLACEMENT_TYPE_RABBIT,Talking:'你知道月亮上那些大大小小的坑洞是怎麼形成的嗎？那些是隕石撞出來的哦！因為月亮沒有大氣層，隕石直接砸在表面，久而久之就變成現在這樣啦！',point:'隕石撞出來'},
    { x: 2, y: 11, type: PLACEMENT_TYPE_RABBIT,Talking:'嘿嘿，在月亮上跳起來感覺超輕飄飄的，因為月亮的重力只有地球的1/6！所以在那裡走路，就像是在慢動作跳舞一樣呢',point:'月亮的重力只有地球的1/6'},
    { x: 14, y: 2, type: PLACEMENT_TYPE_RABBIT,Talking:'月亮其實不會自己發光哦！它就像一面大鏡子，把太陽的光反射回來，所以我們才能在夜晚看到亮亮的月亮！',point:'把太陽的光反射回來'},

    { x: 4, y: 11, type: PLACEMENT_TYPE_SWITCH_DOOR,isRaised:false },
    { x: 6, y: 6, type: PLACEMENT_TYPE_SWITCH_DOOR,isRaised:true },
    { x: 6, y: 12, type: PLACEMENT_TYPE_SWITCH_DOOR,isRaised:true },
    { x: 14, y: 9, type: PLACEMENT_TYPE_SWITCH_DOOR,isRaised:true },
    { x: 8, y: 6, type: PLACEMENT_TYPE_SWITCH },
    { x: 10, y: 12, type: PLACEMENT_TYPE_SWITCH },
    
    { x: 2, y: 4, type: PLACEMENT_TYPE_CONVEYOR,direction:'DOWN' },
    { x: 2, y: 9, type: PLACEMENT_TYPE_CONVEYOR,direction:'UP' },
    { x: 4, y: 2, type: PLACEMENT_TYPE_CONVEYOR,direction:'LEFT' },
    { x: 7, y: 5, type: PLACEMENT_TYPE_CONVEYOR,direction:'LEFT' },
    { x: 7, y: 7, type: PLACEMENT_TYPE_CONVEYOR,direction:'DOWN' },
    { x: 8, y: 7, type: PLACEMENT_TYPE_CONVEYOR,direction:'DOWN' },
    { x: 9, y: 5, type: PLACEMENT_TYPE_CONVEYOR,direction:'RIGHT' },
    { x: 9, y: 7, type: PLACEMENT_TYPE_CONVEYOR,direction:'DOWN' },
    





    

    
  ],
};

export default DemoLevel2;
