import {
  LEVEL_THEMES,
  PLACEMENT_TYPE_FLOUR,
  PLACEMENT_TYPE_GOAL,
  PLACEMENT_TYPE_HERO,
  PLACEMENT_TYPE_WALL,
  PLACEMENT_TYPE_LOCK,
  PLACEMENT_TYPE_KEY,
  PLACEMENT_TYPE_WATER,
  PLACEMENT_TYPE_WATER_PICKUP,
  PLACEMENT_TYPE_GROUND_ENEMY,
  PLACEMENT_TYPE_FLYING_ENEMY,
  PLACEMENT_TYPE_ROAMING_ENEMY,
  PLACEMENT_TYPE_CONVEYOR,
  PLACEMENT_TYPE_ICE,
  PLACEMENT_TYPE_ICE_PICKUP,
  PLACEMENT_TYPE_FIRE,
  PLACEMENT_TYPE_FIRE_PICKUP,
  PLACEMENT_TYPE_SWITCH_DOOR,
  PLACEMENT_TYPE_SWITCH,
  PLACEMENT_TYPE_TELEPORT,
  PLACEMENT_TYPE_THIEF,
  PLACEMENT_TYPE_CIABATTA,
  PLACEMENT_TYPE_RABBIT,
} from "../helpers/consts";
const DemoLevel3 = {
  theme: LEVEL_THEMES.GRAY,
  tilesWidth: 12,
  tilesHeight: 12,
  placements: [
    { x: 1, y: 8, type: PLACEMENT_TYPE_HERO },
    { x: 2, y: 2, type: PLACEMENT_TYPE_GOAL },

    { x: 8, y: 5, type: PLACEMENT_TYPE_SWITCH_DOOR, isRaised: true },
    { x: 8, y: 6, type: PLACEMENT_TYPE_SWITCH_DOOR, isRaised: true },
    { x: 8, y: 7, type: PLACEMENT_TYPE_SWITCH_DOOR, isRaised: true },
    { x: 8, y: 8, type: PLACEMENT_TYPE_SWITCH_DOOR, isRaised: true },
    { x: 8, y: 9, type: PLACEMENT_TYPE_SWITCH_DOOR, isRaised: true },
    { x: 8, y: 10, type: PLACEMENT_TYPE_SWITCH_DOOR, isRaised: false },
    { x: 9, y: 5, type: PLACEMENT_TYPE_SWITCH_DOOR, isRaised: true },
    // { x: 9, y: 8, type: PLACEMENT_TYPE_SWITCH_DOOR, isRaised: false },
    { x: 10, y: 5, type: PLACEMENT_TYPE_SWITCH_DOOR, isRaised: true },
    { x: 11, y: 5, type: PLACEMENT_TYPE_SWITCH_DOOR, isRaised: true },
    { x: 11, y: 6, type: PLACEMENT_TYPE_SWITCH_DOOR, isRaised: true },
    { x: 11, y: 7, type: PLACEMENT_TYPE_SWITCH_DOOR, isRaised: true },
    { x: 11, y: 8, type: PLACEMENT_TYPE_SWITCH_DOOR, isRaised: true },
    { x: 11, y: 9, type: PLACEMENT_TYPE_SWITCH_DOOR, isRaised: true },
    { x: 11, y: 10, type: PLACEMENT_TYPE_SWITCH_DOOR, isRaised: false },
    { x: 9, y: 7, type: PLACEMENT_TYPE_SWITCH },

    // { x: 9, y: 9, type: PLACEMENT_TYPE_THIEF},

    { x: 2, y: 5, type: PLACEMENT_TYPE_WALL },
    { x: 2, y: 7, type: PLACEMENT_TYPE_WALL },
    { x: 2, y: 9, type: PLACEMENT_TYPE_WALL },
    { x: 2, y: 10, type: PLACEMENT_TYPE_WALL },
    { x: 2, y: 11, type: PLACEMENT_TYPE_WALL },
    { x: 3, y: 5, type: PLACEMENT_TYPE_WALL },
    { x: 3, y: 7, type: PLACEMENT_TYPE_WALL },
    { x: 3, y: 11, type: PLACEMENT_TYPE_WALL },
    { x: 4, y: 5, type: PLACEMENT_TYPE_WALL },
    { x: 4, y: 7, type: PLACEMENT_TYPE_WALL },
    { x: 4, y: 9, type: PLACEMENT_TYPE_WALL },
    { x: 4, y: 11, type: PLACEMENT_TYPE_WALL },
    { x: 5, y: 5, type: PLACEMENT_TYPE_WALL },
    { x: 5, y: 7, type: PLACEMENT_TYPE_WALL },
    { x: 5, y: 9, type: PLACEMENT_TYPE_WALL },
    { x: 5, y: 11, type: PLACEMENT_TYPE_WALL },
    { x: 6, y: 5, type: PLACEMENT_TYPE_WALL },
    { x: 6, y: 7, type: PLACEMENT_TYPE_WALL },
    { x: 6, y: 9, type: PLACEMENT_TYPE_WALL },
    // { x: 6, y: 11, type: PLACEMENT_TYPE_WALL },
    { x: 7, y: 5, type: PLACEMENT_TYPE_WALL },
    { x: 7, y: 6, type: PLACEMENT_TYPE_WALL },
    { x: 7, y: 7, type: PLACEMENT_TYPE_WALL },
    { x: 7, y: 8, type: PLACEMENT_TYPE_WALL },
    { x: 7, y: 11, type: PLACEMENT_TYPE_WALL },
    { x: 8, y: 11, type: PLACEMENT_TYPE_WALL },
    { x: 9, y: 11, type: PLACEMENT_TYPE_WALL },
    { x: 10, y: 11, type: PLACEMENT_TYPE_WALL },
    { x: 11, y: 11, type: PLACEMENT_TYPE_WALL },

    { x: 1, y: 4, type: PLACEMENT_TYPE_WATER },
    { x: 1, y: 5, type: PLACEMENT_TYPE_WATER },
    { x: 1, y: 6, type: PLACEMENT_TYPE_WATER },
    { x: 1, y: 10, type: PLACEMENT_TYPE_WATER },
    { x: 1, y: 11, type: PLACEMENT_TYPE_WATER },
    { x: 1, y: 12, type: PLACEMENT_TYPE_WATER },
    { x: 2, y: 4, type: PLACEMENT_TYPE_WATER },
    { x: 2, y: 12, type: PLACEMENT_TYPE_WATER },
    { x: 3, y: 4, type: PLACEMENT_TYPE_WATER },
    { x: 3, y: 12, type: PLACEMENT_TYPE_WATER },
    { x: 4, y: 4, type: PLACEMENT_TYPE_WATER },
    { x: 4, y: 12, type: PLACEMENT_TYPE_WATER },
    { x: 5, y: 4, type: PLACEMENT_TYPE_WATER },
    { x: 5, y: 12, type: PLACEMENT_TYPE_WATER },
    { x: 6, y: 4, type: PLACEMENT_TYPE_WATER },
    { x: 6, y: 12, type: PLACEMENT_TYPE_WATER },
    { x: 7, y: 4, type: PLACEMENT_TYPE_WATER },
    { x: 7, y: 12, type: PLACEMENT_TYPE_WATER },
    { x: 8, y: 4, type: PLACEMENT_TYPE_WATER },
    { x: 8, y: 12, type: PLACEMENT_TYPE_WATER },
    { x: 9, y: 4, type: PLACEMENT_TYPE_WATER },
    { x: 9, y: 12, type: PLACEMENT_TYPE_WATER },
    { x: 10, y: 4, type: PLACEMENT_TYPE_WATER },
    { x: 10, y: 12, type: PLACEMENT_TYPE_WATER },
    { x: 11, y: 4, type: PLACEMENT_TYPE_WATER },
    // { x: 11, y: 5, type: PLACEMENT_TYPE_WATER },
    // { x: 11, y: 6, type: PLACEMENT_TYPE_WATER },
    // { x: 11, y: 7, type: PLACEMENT_TYPE_WATER },
    // { x: 11, y: 8, type: PLACEMENT_TYPE_WATER },
    // { x: 11, y: 9, type: PLACEMENT_TYPE_WATER },
    { x: 11, y: 12, type: PLACEMENT_TYPE_WATER },
    { x: 12, y: 4, type: PLACEMENT_TYPE_WATER },
    { x: 12, y: 5, type: PLACEMENT_TYPE_WATER },
    { x: 12, y: 6, type: PLACEMENT_TYPE_WATER },
    { x: 12, y: 7, type: PLACEMENT_TYPE_WATER },
    { x: 12, y: 8, type: PLACEMENT_TYPE_WATER },
    { x: 12, y: 9, type: PLACEMENT_TYPE_WATER },
    { x: 12, y: 10, type: PLACEMENT_TYPE_WATER },
    { x: 12, y: 11, type: PLACEMENT_TYPE_WATER },
    { x: 12, y: 12, type: PLACEMENT_TYPE_WATER },

    { x: 6, y: 8, type: PLACEMENT_TYPE_WATER_PICKUP },

    { x: 9, y: 6, type: PLACEMENT_TYPE_RABBIT,Talking:"你知道月亮的高度角嗎？就是月亮跟地平線之間的角度！",point:'月亮跟地平線之間的角度'},
    { x: 6, y: 11, type: PLACEMENT_TYPE_RABBIT,Talking:"高度角0度的時候，月亮剛好就在地平線上哦！這時候就是月亮剛升起或快要落下的時候，可以多觀察看看喔！",point:'0度的時候，月亮剛好就在地平線上哦'},
    { x: 6, y: 6, type: PLACEMENT_TYPE_RABBIT,Talking:"你知道嗎？用拳頭來測量天空的高度角，一個拳頭大約是10度哦！這樣就能大概估算月亮離地平線有多高啦！",point:'一個拳頭大約是10度'},
    { x: 11, y: 2, type: PLACEMENT_TYPE_RABBIT,Talking:"高度角是用「度」來表示的哦！就像圓有360度一樣，天空的角度也是這樣測量的！",point:'「度」'},

    { x: 3, y: 10, type: PLACEMENT_TYPE_KEY,color:'GREEN'},
    { x: 2, y: 6, type: PLACEMENT_TYPE_LOCK,color:'GREEN'},
    { x: 9, y: 10, type: PLACEMENT_TYPE_KEY, color:'BLUE'},
    { x: 3, y: 9, type: PLACEMENT_TYPE_LOCK, color:'BLUE'},

    { x: 1, y: 7, type: PLACEMENT_TYPE_CONVEYOR,direction:'UP' },
    { x: 1, y: 9, type: PLACEMENT_TYPE_CONVEYOR,direction:'DOWN' },
    { x: 2, y: 3, type: PLACEMENT_TYPE_CONVEYOR,direction:'DOWN' },
    { x: 7, y: 9, type: PLACEMENT_TYPE_CONVEYOR,direction:'DOWN' },
    { x: 11, y: 3, type: PLACEMENT_TYPE_CONVEYOR,direction:'DOWN' },

    { x: 1, y: 1, type: PLACEMENT_TYPE_ICE,corner:'TOP_LEFT'},
    { x: 1, y: 2, type: PLACEMENT_TYPE_ICE},
    { x: 1, y: 3, type: PLACEMENT_TYPE_ICE,corner:'BOTTOM_LEFT'},
    { x: 2, y: 1, type: PLACEMENT_TYPE_ICE},
    { x: 3, y: 1, type: PLACEMENT_TYPE_ICE},
    { x: 3, y: 2, type: PLACEMENT_TYPE_ICE},
    { x: 3, y: 3, type: PLACEMENT_TYPE_ICE},
    { x: 4, y: 1, type: PLACEMENT_TYPE_ICE},
    { x: 4, y: 2, type: PLACEMENT_TYPE_ICE},
    { x: 4, y: 3, type: PLACEMENT_TYPE_ICE},
    { x: 5, y: 1, type: PLACEMENT_TYPE_ICE},
    { x: 5, y: 2, type: PLACEMENT_TYPE_ICE},
    { x: 5, y: 3, type: PLACEMENT_TYPE_ICE},
    { x: 6, y: 1, type: PLACEMENT_TYPE_ICE},
    { x: 6, y: 2, type: PLACEMENT_TYPE_ICE},
    { x: 6, y: 3, type: PLACEMENT_TYPE_ICE},
    { x: 7, y: 1, type: PLACEMENT_TYPE_ICE},
    { x: 7, y: 2, type: PLACEMENT_TYPE_ICE},
    { x: 7, y: 3, type: PLACEMENT_TYPE_ICE},
    { x: 8, y: 1, type: PLACEMENT_TYPE_ICE},
    { x: 8, y: 2, type: PLACEMENT_TYPE_ICE},
    { x: 8, y: 3, type: PLACEMENT_TYPE_ICE},
    { x: 9, y: 1, type: PLACEMENT_TYPE_ICE},
    { x: 9, y: 2, type: PLACEMENT_TYPE_ICE},
    { x: 9, y: 3, type: PLACEMENT_TYPE_ICE},
    { x: 10, y: 1, type: PLACEMENT_TYPE_ICE},
    { x: 10, y: 2, type: PLACEMENT_TYPE_ICE},
    { x: 10, y: 3, type: PLACEMENT_TYPE_ICE},
    { x: 11, y: 1, type: PLACEMENT_TYPE_ICE},
    { x: 11, y: 2, type: PLACEMENT_TYPE_ICE},
    { x: 12, y: 1, type: PLACEMENT_TYPE_ICE,corner:'TOP_RIGHT'},
    { x: 12, y: 2, type: PLACEMENT_TYPE_ICE},
    { x: 12, y: 3, type: PLACEMENT_TYPE_ICE,corner:'BOTTOM_RIGHT'},

    { x: 5, y: 10, type: PLACEMENT_TYPE_ICE_PICKUP},

    { x: 10, y: 10, type: PLACEMENT_TYPE_GROUND_ENEMY},

    { x: 12, y: 1, type: PLACEMENT_TYPE_FLYING_ENEMY},

  ],
};

export default DemoLevel3;