import {
  LEVEL_THEMES,
  PLACEMENT_TYPE_FLOUR,
  PLACEMENT_TYPE_GOAL,
  PLACEMENT_TYPE_HERO,
  PLACEMENT_TYPE_WALL,
  PLACEMENT_TYPE_LOCK,
  PLACEMENT_TYPE_KEY,
  PLACEMENT_TYPE_WATER,
  PLACEMENT_TYPE_WATER_PICKUP,
  PLACEMENT_TYPE_GROUND_ENEMY,
  PLACEMENT_TYPE_FLYING_ENEMY,
  PLACEMENT_TYPE_ROAMING_ENEMY,
  PLACEMENT_TYPE_CONVEYOR,
  PLACEMENT_TYPE_ICE,
  PLACEMENT_TYPE_ICE_PICKUP,
  PLACEMENT_TYPE_FIRE,
  PLACEMENT_TYPE_FIRE_PICKUP,
  PLACEMENT_TYPE_SWITCH_DOOR,
  PLACEMENT_TYPE_SWITCH,
  PLACEMENT_TYPE_TELEPORT,
  PLACEMENT_TYPE_THIEF,
  PLACEMENT_TYPE_CIABATTA,
  PLACEMENT_TYPE_RABBIT,
} from "../helpers/consts";
const DemoLevel1 = {
  theme: LEVEL_THEMES.BLUE,
  tilesWidth: 12,
  tilesHeight: 12,
  placements: [
    { x: 1, y: 8, type: PLACEMENT_TYPE_HERO },
    { x: 2, y: 2, type: PLACEMENT_TYPE_GOAL },

    { x: 8, y: 5, type: PLACEMENT_TYPE_SWITCH_DOOR, isRaised: true },
    { x: 8, y: 6, type: PLACEMENT_TYPE_SWITCH_DOOR, isRaised: true },
    { x: 8, y: 7, type: PLACEMENT_TYPE_SWITCH_DOOR, isRaised: true },
    { x: 8, y: 8, type: PLACEMENT_TYPE_SWITCH_DOOR, isRaised: true },
    { x: 8, y: 9, type: PLACEMENT_TYPE_SWITCH_DOOR, isRaised: true },
    { x: 8, y: 10, type: PLACEMENT_TYPE_SWITCH_DOOR, isRaised: false },
    { x: 9, y: 5, type: PLACEMENT_TYPE_SWITCH_DOOR, isRaised: true },
    { x: 9, y: 8, type: PLACEMENT_TYPE_SWITCH_DOOR, isRaised: false },
    { x: 10, y: 5, type: PLACEMENT_TYPE_SWITCH_DOOR, isRaised: true },
    { x: 10, y: 6, type: PLACEMENT_TYPE_SWITCH_DOOR, isRaised: true },
    { x: 10, y: 7, type: PLACEMENT_TYPE_SWITCH_DOOR, isRaised: true },
    { x: 10, y: 8, type: PLACEMENT_TYPE_SWITCH_DOOR, isRaised: true },
    { x: 10, y: 9, type: PLACEMENT_TYPE_SWITCH_DOOR, isRaised: true },
    { x: 11, y: 10, type: PLACEMENT_TYPE_SWITCH_DOOR, isRaised: false },
    { x: 9, y: 7, type: PLACEMENT_TYPE_SWITCH },

    { x: 9, y: 9, type: PLACEMENT_TYPE_THIEF},

    { x: 2, y: 5, type: PLACEMENT_TYPE_WALL },
    { x: 2, y: 7, type: PLACEMENT_TYPE_WALL },
    { x: 2, y: 9, type: PLACEMENT_TYPE_WALL },
    { x: 2, y: 10, type: PLACEMENT_TYPE_WALL },
    { x: 2, y: 11, type: PLACEMENT_TYPE_WALL },
    { x: 3, y: 5, type: PLACEMENT_TYPE_WALL },
    { x: 3, y: 7, type: PLACEMENT_TYPE_WALL },
    { x: 3, y: 11, type: PLACEMENT_TYPE_WALL },
    { x: 4, y: 5, type: PLACEMENT_TYPE_WALL },
    { x: 4, y: 7, type: PLACEMENT_TYPE_WALL },
    { x: 4, y: 9, type: PLACEMENT_TYPE_WALL },
    { x: 4, y: 11, type: PLACEMENT_TYPE_WALL },
    { x: 5, y: 5, type: PLACEMENT_TYPE_WALL },
    { x: 5, y: 7, type: PLACEMENT_TYPE_WALL },
    { x: 5, y: 9, type: PLACEMENT_TYPE_WALL },
    { x: 5, y: 11, type: PLACEMENT_TYPE_WALL },
    { x: 6, y: 5, type: PLACEMENT_TYPE_WALL },
    { x: 6, y: 7, type: PLACEMENT_TYPE_WALL },
    { x: 6, y: 9, type: PLACEMENT_TYPE_WALL },
    { x: 6, y: 11, type: PLACEMENT_TYPE_WALL },
    { x: 7, y: 5, type: PLACEMENT_TYPE_WALL },
    { x: 7, y: 6, type: PLACEMENT_TYPE_WALL },
    { x: 7, y: 7, type: PLACEMENT_TYPE_WALL },
    { x: 7, y: 8, type: PLACEMENT_TYPE_WALL },
    { x: 7, y: 11, type: PLACEMENT_TYPE_WALL },
    { x: 8, y: 11, type: PLACEMENT_TYPE_WALL },
    { x: 9, y: 11, type: PLACEMENT_TYPE_WALL },
    { x: 10, y: 11, type: PLACEMENT_TYPE_WALL },
    { x: 11, y: 11, type: PLACEMENT_TYPE_WALL },

    { x: 1, y: 4, type: PLACEMENT_TYPE_WATER },
    { x: 1, y: 5, type: PLACEMENT_TYPE_WATER },
    { x: 1, y: 6, type: PLACEMENT_TYPE_WATER },
    { x: 1, y: 10, type: PLACEMENT_TYPE_WATER },
    { x: 1, y: 11, type: PLACEMENT_TYPE_WATER },
    { x: 1, y: 12, type: PLACEMENT_TYPE_WATER },
    { x: 2, y: 4, type: PLACEMENT_TYPE_WATER },
    { x: 2, y: 12, type: PLACEMENT_TYPE_WATER },
    { x: 3, y: 4, type: PLACEMENT_TYPE_WATER },
    { x: 3, y: 12, type: PLACEMENT_TYPE_WATER },
    { x: 4, y: 4, type: PLACEMENT_TYPE_WATER },
    { x: 4, y: 12, type: PLACEMENT_TYPE_WATER },
    { x: 5, y: 4, type: PLACEMENT_TYPE_WATER },
    { x: 5, y: 12, type: PLACEMENT_TYPE_WATER },
    { x: 6, y: 4, type: PLACEMENT_TYPE_WATER },
    { x: 6, y: 12, type: PLACEMENT_TYPE_WATER },
    { x: 7, y: 4, type: PLACEMENT_TYPE_WATER },
    { x: 7, y: 12, type: PLACEMENT_TYPE_WATER },
    { x: 8, y: 4, type: PLACEMENT_TYPE_WATER },
    { x: 8, y: 12, type: PLACEMENT_TYPE_WATER },
    { x: 9, y: 4, type: PLACEMENT_TYPE_WATER },
    { x: 9, y: 12, type: PLACEMENT_TYPE_WATER },
    { x: 10, y: 4, type: PLACEMENT_TYPE_WATER },
    { x: 10, y: 12, type: PLACEMENT_TYPE_WATER },
    { x: 11, y: 4, type: PLACEMENT_TYPE_WATER },
    { x: 11, y: 5, type: PLACEMENT_TYPE_WATER },
    { x: 11, y: 6, type: PLACEMENT_TYPE_WATER },
    { x: 11, y: 7, type: PLACEMENT_TYPE_WATER },
    { x: 11, y: 8, type: PLACEMENT_TYPE_WATER },
    { x: 11, y: 9, type: PLACEMENT_TYPE_WATER },
    { x: 11, y: 12, type: PLACEMENT_TYPE_WATER },
    { x: 12, y: 4, type: PLACEMENT_TYPE_WATER },
    { x: 12, y: 5, type: PLACEMENT_TYPE_WATER },
    { x: 12, y: 6, type: PLACEMENT_TYPE_WATER },
    { x: 12, y: 7, type: PLACEMENT_TYPE_WATER },
    { x: 12, y: 8, type: PLACEMENT_TYPE_WATER },
    { x: 12, y: 9, type: PLACEMENT_TYPE_WATER },
    { x: 12, y: 10, type: PLACEMENT_TYPE_WATER },
    { x: 12, y: 11, type: PLACEMENT_TYPE_WATER },
    { x: 12, y: 12, type: PLACEMENT_TYPE_WATER },

    { x: 6, y: 8, type: PLACEMENT_TYPE_WATER_PICKUP },
    { x: 9, y: 6, type: PLACEMENT_TYPE_WATER_PICKUP },
    

    { x: 6, y: 6, type: PLACEMENT_TYPE_RABBIT,Talking:"科學家認為月球形成於約 45 億年前，可能是因為一顆火星大小的天體撞擊地球，噴出的碎片逐漸聚集成月球。月球表面表面主要由各式各樣的石頭與岩石組成，而且缺乏大氣層，因此沒有風或液態水。"},
    { x: 11, y: 2, type: PLACEMENT_TYPE_RABBIT,Talking:"月球的引力影響地球的潮汐，使海水定期漲落，並穩定地球自轉軸，維持氣候穩定。此外，月球的不同相位（如滿月、新月）影響農耕、文化與傳統節日，例如中秋節即與滿月有關。"},

    { x: 3, y: 10, type: PLACEMENT_TYPE_KEY,color:'GREEN'},
    { x: 2, y: 6, type: PLACEMENT_TYPE_LOCK,color:'GREEN'},
    { x: 9, y: 10, type: PLACEMENT_TYPE_KEY, color:'BLUE'},
    { x: 3, y: 9, type: PLACEMENT_TYPE_LOCK, color:'BLUE'},

    { x: 1, y: 7, type: PLACEMENT_TYPE_CONVEYOR,direction:'UP' },
    { x: 1, y: 9, type: PLACEMENT_TYPE_CONVEYOR,direction:'DOWN' },
    { x: 2, y: 3, type: PLACEMENT_TYPE_CONVEYOR,direction:'DOWN' },
    { x: 7, y: 9, type: PLACEMENT_TYPE_CONVEYOR,direction:'DOWN' },
    { x: 11, y: 3, type: PLACEMENT_TYPE_CONVEYOR,direction:'DOWN' },

    { x: 1, y: 1, type: PLACEMENT_TYPE_ICE,corner:'TOP_LEFT'},
    { x: 1, y: 2, type: PLACEMENT_TYPE_ICE},
    { x: 1, y: 3, type: PLACEMENT_TYPE_ICE,corner:'BOTTOM_LEFT'},
    { x: 2, y: 1, type: PLACEMENT_TYPE_ICE},
    { x: 3, y: 1, type: PLACEMENT_TYPE_ICE},
    { x: 3, y: 2, type: PLACEMENT_TYPE_ICE},
    { x: 3, y: 3, type: PLACEMENT_TYPE_ICE},
    { x: 4, y: 1, type: PLACEMENT_TYPE_ICE},
    { x: 4, y: 2, type: PLACEMENT_TYPE_ICE},
    { x: 4, y: 3, type: PLACEMENT_TYPE_ICE},
    { x: 5, y: 1, type: PLACEMENT_TYPE_ICE},
    { x: 5, y: 2, type: PLACEMENT_TYPE_ICE},
    { x: 5, y: 3, type: PLACEMENT_TYPE_ICE},
    { x: 6, y: 1, type: PLACEMENT_TYPE_ICE},
    { x: 6, y: 2, type: PLACEMENT_TYPE_ICE},
    { x: 6, y: 3, type: PLACEMENT_TYPE_ICE},
    { x: 7, y: 1, type: PLACEMENT_TYPE_ICE},
    { x: 7, y: 2, type: PLACEMENT_TYPE_ICE},
    { x: 7, y: 3, type: PLACEMENT_TYPE_ICE},
    { x: 8, y: 1, type: PLACEMENT_TYPE_ICE},
    { x: 8, y: 2, type: PLACEMENT_TYPE_ICE},
    { x: 8, y: 3, type: PLACEMENT_TYPE_ICE},
    { x: 9, y: 1, type: PLACEMENT_TYPE_ICE},
    { x: 9, y: 2, type: PLACEMENT_TYPE_ICE},
    { x: 9, y: 3, type: PLACEMENT_TYPE_ICE},
    { x: 10, y: 1, type: PLACEMENT_TYPE_ICE},
    { x: 10, y: 2, type: PLACEMENT_TYPE_ICE},
    { x: 10, y: 3, type: PLACEMENT_TYPE_ICE},
    { x: 11, y: 1, type: PLACEMENT_TYPE_ICE},
    { x: 11, y: 2, type: PLACEMENT_TYPE_ICE},
    { x: 12, y: 1, type: PLACEMENT_TYPE_ICE,corner:'TOP_RIGHT'},
    { x: 12, y: 2, type: PLACEMENT_TYPE_ICE},
    { x: 12, y: 3, type: PLACEMENT_TYPE_ICE,corner:'BOTTOM_RIGHT'},

    { x: 5, y: 10, type: PLACEMENT_TYPE_ICE_PICKUP},

    { x: 10, y: 10, type: PLACEMENT_TYPE_GROUND_ENEMY},

    { x: 12, y: 1, type: PLACEMENT_TYPE_FLYING_ENEMY},

  ],
};

export default DemoLevel1;
