import {
  LEVEL_THEMES,
  PLACEMENT_TYPE_FLOUR,
  PLACEMENT_TYPE_GOAL,
  PLACEMENT_TYPE_HERO,
  PLACEMENT_TYPE_WALL,
  PLACEMENT_TYPE_LOCK,
  PLACEMENT_TYPE_KEY,
  PLACEMENT_TYPE_WATER,
  PLACEMENT_TYPE_WATER_PICKUP,
  PLACEMENT_TYPE_GROUND_ENEMY,
  PLACEMENT_TYPE_FLYING_ENEMY,
  PLACEMENT_TYPE_ROAMING_ENEMY,
  PLACEMENT_TYPE_CONVEYOR,
  PLACEMENT_TYPE_ICE,
  PLACEMENT_TYPE_ICE_PICKUP,
  PLACEMENT_TYPE_FIRE,
  PLACEMENT_TYPE_FIRE_PICKUP,
  PLACEMENT_TYPE_SWITCH_DOOR,
  PLACEMENT_TYPE_SWITCH,
  PLACEMENT_TYPE_TELEPORT,
  PLACEMENT_TYPE_THIEF,
  PLACEMENT_TYPE_CIABATTA,
  PLACEMENT_TYPE_RABBIT,
} from "../helpers/consts";
const DemoLevel4 = {
  theme: LEVEL_THEMES.BLUE,
  tilesWidth: 13,
  tilesHeight: 13,
  placements: [
    { x: 7, y: 7, type: PLACEMENT_TYPE_HERO },
    { x: 12, y: 2, type: PLACEMENT_TYPE_GOAL },

    { x: 11, y: 2, type: PLACEMENT_TYPE_LOCK },
    { x: 6, y: 5, type: PLACEMENT_TYPE_KEY },

    { x: 2, y: 4, type: PLACEMENT_TYPE_RABBIT,Talking:"要做一個簡單的高度角量角器，只需要紙板、量角器、繩子和吸管哦！用這些材料就能測量月亮的高度角，超有趣的呢！"},
    { x: 5, y: 2, type: PLACEMENT_TYPE_RABBIT,Talking:"當你用高度角量角器時，記得要對準月亮哦！這樣才能測出月亮離地平線的角度，看看它現在在哪裡哦！"},
    { x: 10, y: 12, type: PLACEMENT_TYPE_RABBIT,Talking:"當高度角量角器上的繩子指向90度時，代表月亮就在你的頭頂正上方哦！這就是「天頂」的位置，超級高的呢！"},
    { x: 11, y: 1, type: PLACEMENT_TYPE_RABBIT,Talking:"要測量月亮的高度角，最方便的就是用「高度角量角器」啦！只要對準月亮，看看繩子指向幾度，就能知道它離地平線有多高哦！"},

    { x: 3, y: 13, type:PLACEMENT_TYPE_WALL},
    { x: 4, y: 6, type:PLACEMENT_TYPE_WALL},
    { x: 4, y: 12, type:PLACEMENT_TYPE_WALL},
    { x: 8, y: 3, type:PLACEMENT_TYPE_WALL},
    { x: 9, y: 5, type:PLACEMENT_TYPE_WALL},
    { x: 9, y: 10, type:PLACEMENT_TYPE_WALL},
    { x: 13, y: 6, type:PLACEMENT_TYPE_WALL},
    { x: 13, y: 11, type:PLACEMENT_TYPE_WALL},

    { x: 1, y: 6, type:PLACEMENT_TYPE_WATER},
    { x: 3, y: 1, type:PLACEMENT_TYPE_WATER},
    { x: 3, y: 11, type:PLACEMENT_TYPE_WATER},
    { x: 4, y: 7, type:PLACEMENT_TYPE_WATER},
    { x: 4, y: 13, type:PLACEMENT_TYPE_WATER},
    { x: 5, y: 13, type:PLACEMENT_TYPE_WATER},
    { x: 6, y: 2, type:PLACEMENT_TYPE_WATER},
    { x: 6, y: 10, type:PLACEMENT_TYPE_WATER},
    { x: 8, y: 12, type:PLACEMENT_TYPE_WATER},
    { x: 9, y: 3, type:PLACEMENT_TYPE_WATER},
    { x: 10, y: 9, type:PLACEMENT_TYPE_WATER},
    { x: 12, y: 1, type:PLACEMENT_TYPE_WATER},
    { x: 12, y: 11, type:PLACEMENT_TYPE_WATER},
    { x: 13, y: 7, type:PLACEMENT_TYPE_WATER},

    { x: 1, y: 1, type:PLACEMENT_TYPE_ICE,corner:"TOP_LEFT"},
    { x: 1, y: 2, type:PLACEMENT_TYPE_ICE},
    { x: 1, y: 3, type:PLACEMENT_TYPE_ICE},
    { x: 1, y: 4, type:PLACEMENT_TYPE_ICE},
    { x: 1, y: 5, type:PLACEMENT_TYPE_ICE},
    { x: 1, y: 7, type:PLACEMENT_TYPE_ICE},
    { x: 1, y: 8, type:PLACEMENT_TYPE_ICE},
    { x: 1, y: 9, type:PLACEMENT_TYPE_ICE},
    { x: 1, y: 10, type:PLACEMENT_TYPE_ICE},
    { x: 1, y: 11, type:PLACEMENT_TYPE_ICE},
    { x: 1, y: 12, type:PLACEMENT_TYPE_ICE},
    { x: 1, y: 13, type:PLACEMENT_TYPE_ICE,corner:"BOTTOM_LEFT"},

    { x: 2, y: 1, type:PLACEMENT_TYPE_ICE},
    { x: 2, y: 2, type:PLACEMENT_TYPE_ICE},
    { x: 2, y: 3, type:PLACEMENT_TYPE_ICE},
    { x: 2, y: 5, type:PLACEMENT_TYPE_ICE},
    { x: 2, y: 6, type:PLACEMENT_TYPE_ICE},
    { x: 2, y: 7, type:PLACEMENT_TYPE_ICE},
    { x: 2, y: 8, type:PLACEMENT_TYPE_ICE},
    { x: 2, y: 9, type:PLACEMENT_TYPE_ICE},
    { x: 2, y: 10, type:PLACEMENT_TYPE_ICE},
    { x: 2, y: 11, type:PLACEMENT_TYPE_ICE},
    { x: 2, y: 12, type:PLACEMENT_TYPE_ICE},
    { x: 2, y: 13, type:PLACEMENT_TYPE_ICE},

    { x: 3, y: 2, type:PLACEMENT_TYPE_ICE},
    { x: 3, y: 3, type:PLACEMENT_TYPE_ICE},
    { x: 3, y: 4, type:PLACEMENT_TYPE_ICE},
    { x: 3, y: 5, type:PLACEMENT_TYPE_ICE},
    { x: 3, y: 6, type:PLACEMENT_TYPE_ICE},
    { x: 3, y: 7, type:PLACEMENT_TYPE_ICE},
    { x: 3, y: 8, type:PLACEMENT_TYPE_ICE},
    { x: 3, y: 9, type:PLACEMENT_TYPE_ICE},
    { x: 3, y: 10, type:PLACEMENT_TYPE_ICE},
    { x: 3, y: 12, type:PLACEMENT_TYPE_ICE},

    { x: 4, y: 1, type:PLACEMENT_TYPE_ICE},
    { x: 4, y: 2, type:PLACEMENT_TYPE_ICE},
    { x: 4, y: 3, type:PLACEMENT_TYPE_ICE},
    { x: 4, y: 4, type:PLACEMENT_TYPE_ICE},
    { x: 4, y: 5, type:PLACEMENT_TYPE_ICE},
    { x: 4, y: 8, type:PLACEMENT_TYPE_ICE},
    { x: 4, y: 9, type:PLACEMENT_TYPE_ICE},
    { x: 4, y: 10, type:PLACEMENT_TYPE_ICE},
    { x: 4, y: 11, type:PLACEMENT_TYPE_ICE},


    { x: 5, y: 1, type:PLACEMENT_TYPE_ICE},
    { x: 5, y: 3, type:PLACEMENT_TYPE_ICE},
    { x: 5, y: 4, type:PLACEMENT_TYPE_ICE},
    { x: 5, y: 5, type:PLACEMENT_TYPE_ICE},
    { x: 5, y: 6, type:PLACEMENT_TYPE_ICE},
    { x: 5, y: 7, type:PLACEMENT_TYPE_ICE},
    { x: 5, y: 8, type:PLACEMENT_TYPE_ICE},
    { x: 5, y: 9, type:PLACEMENT_TYPE_ICE},
    { x: 5, y: 10, type:PLACEMENT_TYPE_ICE},
    { x: 5, y: 11, type:PLACEMENT_TYPE_ICE},
    { x: 5, y: 12, type:PLACEMENT_TYPE_ICE},
  

    { x: 6, y: 1, type:PLACEMENT_TYPE_ICE},
    { x: 6, y: 3, type:PLACEMENT_TYPE_ICE},
    { x: 6, y: 4, type:PLACEMENT_TYPE_ICE},
    { x: 6, y: 5, type:PLACEMENT_TYPE_ICE},
    { x: 6, y: 9, type:PLACEMENT_TYPE_ICE},
    { x: 6, y: 11, type:PLACEMENT_TYPE_ICE},
    { x: 6, y: 12, type:PLACEMENT_TYPE_ICE},
    { x: 6, y: 13, type:PLACEMENT_TYPE_ICE},

    { x: 7, y: 1, type:PLACEMENT_TYPE_ICE},
    { x: 7, y: 2, type:PLACEMENT_TYPE_ICE},
    { x: 7, y: 3, type:PLACEMENT_TYPE_ICE},
    { x: 7, y: 4, type:PLACEMENT_TYPE_ICE},
    { x: 7, y: 5, type:PLACEMENT_TYPE_ICE},
    { x: 7, y: 9, type:PLACEMENT_TYPE_ICE},
    { x: 7, y: 10, type:PLACEMENT_TYPE_ICE},
    { x: 7, y: 11, type:PLACEMENT_TYPE_ICE},
    { x: 7, y: 12, type:PLACEMENT_TYPE_ICE},
    { x: 7, y: 13, type:PLACEMENT_TYPE_ICE},

    { x: 8, y: 1, type:PLACEMENT_TYPE_ICE},
    { x: 8, y: 2, type:PLACEMENT_TYPE_ICE},
    { x: 8, y: 4, type:PLACEMENT_TYPE_ICE},
    { x: 8, y: 5, type:PLACEMENT_TYPE_ICE},
    { x: 8, y: 9, type:PLACEMENT_TYPE_ICE},
    { x: 8, y: 10, type:PLACEMENT_TYPE_ICE},
    { x: 8, y: 11, type:PLACEMENT_TYPE_ICE},
    { x: 8, y: 13, type:PLACEMENT_TYPE_ICE},

    { x: 9, y: 1, type:PLACEMENT_TYPE_ICE},
    { x: 9, y: 2, type:PLACEMENT_TYPE_ICE},
    { x: 9, y: 4, type:PLACEMENT_TYPE_ICE},
    { x: 9, y: 6, type:PLACEMENT_TYPE_ICE},
    { x: 9, y: 7, type:PLACEMENT_TYPE_ICE},
    { x: 9, y: 8, type:PLACEMENT_TYPE_ICE},
    { x: 9, y: 9, type:PLACEMENT_TYPE_ICE},
    { x: 9, y: 11, type:PLACEMENT_TYPE_ICE},
    { x: 9, y: 12, type:PLACEMENT_TYPE_ICE},
    { x: 9, y: 13, type:PLACEMENT_TYPE_ICE},

    { x: 10, y: 1, type:PLACEMENT_TYPE_ICE},
    { x: 10, y: 2, type:PLACEMENT_TYPE_ICE},
    { x: 10, y: 3, type:PLACEMENT_TYPE_ICE},
    { x: 10, y: 4, type:PLACEMENT_TYPE_ICE},
    { x: 10, y: 5, type:PLACEMENT_TYPE_ICE},
    { x: 10, y: 6, type:PLACEMENT_TYPE_ICE},
    { x: 10, y: 7, type:PLACEMENT_TYPE_ICE},
    { x: 10, y: 8, type:PLACEMENT_TYPE_ICE},
    { x: 10, y: 10, type:PLACEMENT_TYPE_ICE},
    { x: 10, y: 11, type:PLACEMENT_TYPE_ICE},
    { x: 10, y: 13, type:PLACEMENT_TYPE_ICE},

    { x: 11, y: 3, type:PLACEMENT_TYPE_ICE},
    { x: 11, y: 4, type:PLACEMENT_TYPE_ICE},
    { x: 11, y: 5, type:PLACEMENT_TYPE_ICE},
    { x: 11, y: 6, type:PLACEMENT_TYPE_ICE},
    { x: 11, y: 7, type:PLACEMENT_TYPE_ICE},
    { x: 11, y: 8, type:PLACEMENT_TYPE_ICE},
    { x: 11, y: 9, type:PLACEMENT_TYPE_ICE},
    { x: 11, y: 10, type:PLACEMENT_TYPE_ICE},
    { x: 11, y: 11, type:PLACEMENT_TYPE_ICE},
    { x: 11, y: 12, type:PLACEMENT_TYPE_ICE},
    { x: 11, y: 13, type:PLACEMENT_TYPE_ICE},

    { x: 12, y: 3, type:PLACEMENT_TYPE_ICE},
    { x: 12, y: 4, type:PLACEMENT_TYPE_ICE},
    { x: 12, y: 5, type:PLACEMENT_TYPE_ICE},
    { x: 12, y: 6, type:PLACEMENT_TYPE_ICE},
    { x: 12, y: 7, type:PLACEMENT_TYPE_ICE},
    { x: 12, y: 8, type:PLACEMENT_TYPE_ICE},
    { x: 12, y: 9, type:PLACEMENT_TYPE_ICE},
    { x: 12, y: 10, type:PLACEMENT_TYPE_ICE},
    { x: 12, y: 12, type:PLACEMENT_TYPE_ICE},
    { x: 12, y: 13, type:PLACEMENT_TYPE_ICE},

    { x: 13, y: 1, type:PLACEMENT_TYPE_ICE,corner:"TOP_RIGHT"},
    { x: 13, y: 2, type:PLACEMENT_TYPE_ICE},
    { x: 13, y: 3, type:PLACEMENT_TYPE_ICE},
    { x: 13, y: 4, type:PLACEMENT_TYPE_ICE},
    { x: 13, y: 5, type:PLACEMENT_TYPE_ICE},
    { x: 13, y: 8, type:PLACEMENT_TYPE_ICE},
    { x: 13, y: 9, type:PLACEMENT_TYPE_ICE},
    { x: 13, y: 10, type:PLACEMENT_TYPE_ICE},
    { x: 13, y: 12, type:PLACEMENT_TYPE_ICE},
    { x: 13, y: 13, type:PLACEMENT_TYPE_ICE,corner:"BOTTOM_RIGHT"},





    
  ],
};

export default DemoLevel4;
