import {
  LEVEL_THEMES,
  PLACEMENT_TYPE_FLOUR,
  PLACEMENT_TYPE_GOAL,
  PLACEMENT_TYPE_HERO,
  PLACEMENT_TYPE_WALL,
  PLACEMENT_TYPE_LOCK,
  PLACEMENT_TYPE_KEY,
  PLACEMENT_TYPE_WATER,
  PLACEMENT_TYPE_WATER_PICKUP,
  PLACEMENT_TYPE_GROUND_ENEMY,
  PLACEMENT_TYPE_FLYING_ENEMY,
  PLACEMENT_TYPE_ROAMING_ENEMY,
  PLACEMENT_TYPE_CONVEYOR,
  PLACEMENT_TYPE_ICE,
  PLACEMENT_TYPE_ICE_PICKUP,
  PLACEMENT_TYPE_FIRE,
  PLACEMENT_TYPE_FIRE_PICKUP,
  PLACEMENT_TYPE_SWITCH_DOOR,
  PLACEMENT_TYPE_SWITCH,
  PLACEMENT_TYPE_TELEPORT,
  PLACEMENT_TYPE_THIEF,
  PLACEMENT_TYPE_CIABATTA,
  PLACEMENT_TYPE_RABBIT,
  PLACEMENT_TYPE_PRINCESS,
} from "../helpers/consts";
const DemoLevel6= {
  theme: LEVEL_THEMES.GRAY,
  tilesWidth: 21,
  tilesHeight: 13,
  placements: [
    { x: 2, y: 2, type: PLACEMENT_TYPE_HERO },
    { x: 19, y: 2, type: PLACEMENT_TYPE_GOAL },

    { x: 8, y: 6, type: PLACEMENT_TYPE_LOCK,color:'BLUE' },
    { x: 20, y: 10, type: PLACEMENT_TYPE_LOCK,color:'BLUE' },
    { x: 2, y: 6, type: PLACEMENT_TYPE_KEY,color:'BLUE' },
    { x: 13, y: 9, type: PLACEMENT_TYPE_KEY,color:'BLUE' },
    { x: 8, y: 2, type: PLACEMENT_TYPE_LOCK,color:'GREEN' },
    { x: 8, y: 11, type: PLACEMENT_TYPE_LOCK,color:'GREEN' },
    { x: 9, y: 10, type: PLACEMENT_TYPE_LOCK,color:'GREEN' },
    { x: 9, y: 12, type: PLACEMENT_TYPE_LOCK,color:'GREEN' },
    { x: 10, y: 11, type: PLACEMENT_TYPE_LOCK,color:'GREEN' },
    { x: 10, y: 6, type: PLACEMENT_TYPE_KEY,color:'GREEN' },

    { x: 10, y: 2, type: PLACEMENT_TYPE_RABBIT,Talking:"當月亮從細細的彎月慢慢變大，變成圓圓的滿月，這個過程叫做「盈月」哦！就像月亮在長大一樣，越來越亮呢！"},
    { x: 13, y: 4, type: PLACEMENT_TYPE_RABBIT,Talking:"當月亮從圓圓的滿月變成細細的彎月，這個過程叫做「虧月」哦！月亮就像在慢慢變小，最後變成新月呢！"},
    { x: 17, y: 13, type: PLACEMENT_TYPE_RABBIT,Talking:"月亮的變化順序是這樣的哦：「新月 → 上弦月 → 滿月 → 下弦月」！這是月亮循環的過程，從完全看不見到圓圓的，再到變小，最後又回到新月啦！"},
    { x: 20, y: 12, type: PLACEMENT_TYPE_RABBIT,Talking:"月亮可不會出現三角形的形狀哦！月亮常見的形狀有圓形、半圓形和彎月形呢！"},

    { x: 1, y: 4, type:PLACEMENT_TYPE_WALL},
    { x: 1, y: 8, type:PLACEMENT_TYPE_WALL},
    { x: 2, y: 8, type:PLACEMENT_TYPE_WALL},
    { x: 2, y: 10, type:PLACEMENT_TYPE_WALL},
    { x: 2, y: 12, type:PLACEMENT_TYPE_WALL},
  
    { x: 3, y: 4, type:PLACEMENT_TYPE_WALL},
    { x: 3, y: 8, type:PLACEMENT_TYPE_WALL},
    { x: 4, y: 1, type:PLACEMENT_TYPE_WALL},
    { x: 4, y: 3, type:PLACEMENT_TYPE_WALL},
    { x: 4, y: 4, type:PLACEMENT_TYPE_WALL},
    { x: 4, y: 5, type:PLACEMENT_TYPE_WALL},
    { x: 4, y: 6, type:PLACEMENT_TYPE_WALL},
    { x: 4, y: 7, type:PLACEMENT_TYPE_WALL},
    { x: 4, y: 8, type:PLACEMENT_TYPE_WALL},
    { x: 4, y: 10, type:PLACEMENT_TYPE_WALL},
    { x: 4, y: 12, type:PLACEMENT_TYPE_WALL},
    { x: 5, y: 4, type:PLACEMENT_TYPE_WALL},
    { x: 5, y: 8, type:PLACEMENT_TYPE_WALL},
    { x: 6, y: 4, type:PLACEMENT_TYPE_WALL},
    { x: 6, y: 8, type:PLACEMENT_TYPE_WALL},
    { x: 7, y: 4, type:PLACEMENT_TYPE_WALL},
    { x: 7, y: 8, type:PLACEMENT_TYPE_WALL},
    { x: 8, y: 1, type:PLACEMENT_TYPE_WALL},
    { x: 8, y: 3, type:PLACEMENT_TYPE_WALL},
    { x: 8, y: 4, type:PLACEMENT_TYPE_WALL},
    { x: 8, y: 5, type:PLACEMENT_TYPE_WALL},
    { x: 8, y: 7, type:PLACEMENT_TYPE_WALL},
    { x: 8, y: 8, type:PLACEMENT_TYPE_WALL},
    { x: 8, y: 10, type:PLACEMENT_TYPE_WALL},
    { x: 8, y: 12, type:PLACEMENT_TYPE_WALL},
    { x: 9, y: 4, type:PLACEMENT_TYPE_WALL},
    { x: 9, y: 8, type:PLACEMENT_TYPE_WALL},
    { x: 10, y: 4, type:PLACEMENT_TYPE_WALL},
    { x: 10, y: 8, type:PLACEMENT_TYPE_WALL},
    { x: 10, y: 10, type:PLACEMENT_TYPE_WALL},
    { x: 10, y: 12, type:PLACEMENT_TYPE_WALL},
    { x: 11, y: 4, type:PLACEMENT_TYPE_WALL},
    { x: 11, y: 8, type:PLACEMENT_TYPE_WALL},

    { x: 12, y: 1, type:PLACEMENT_TYPE_WALL},
    { x: 12, y: 3, type:PLACEMENT_TYPE_WALL},
    { x: 12, y: 4, type:PLACEMENT_TYPE_WALL},
    { x: 12, y: 5, type:PLACEMENT_TYPE_WALL},
    { x: 12, y: 6, type:PLACEMENT_TYPE_WALL},
    { x: 12, y: 7, type:PLACEMENT_TYPE_WALL},
    { x: 12, y: 8, type:PLACEMENT_TYPE_WALL},
    { x: 12, y: 9, type:PLACEMENT_TYPE_WALL},
    { x: 12, y: 10, type:PLACEMENT_TYPE_WALL},
    { x: 12, y: 11, type:PLACEMENT_TYPE_WALL},
    { x: 12, y: 12, type:PLACEMENT_TYPE_WALL},
    { x: 12, y: 13, type:PLACEMENT_TYPE_WALL},
    { x: 14, y: 7, type:PLACEMENT_TYPE_WALL},
    { x: 14, y: 8, type:PLACEMENT_TYPE_WALL},
    { x: 14, y: 9, type:PLACEMENT_TYPE_WALL},
    { x: 14, y: 10, type:PLACEMENT_TYPE_WALL},

    { x: 17, y: 11, type:PLACEMENT_TYPE_WALL},
    { x: 18, y: 12, type:PLACEMENT_TYPE_WALL},
    { x: 18, y: 13, type:PLACEMENT_TYPE_WALL},
    { x: 19, y: 7, type:PLACEMENT_TYPE_WALL},
    { x: 19, y: 10, type:PLACEMENT_TYPE_WALL},
    { x: 21, y: 10, type:PLACEMENT_TYPE_WALL},

    { x: 6, y: 2, type:PLACEMENT_TYPE_TELEPORT},
    { x: 6, y: 6, type:PLACEMENT_TYPE_TELEPORT},
    { x: 3, y: 11, type:PLACEMENT_TYPE_TELEPORT},
    { x: 9, y: 11, type:PLACEMENT_TYPE_TELEPORT},
    
    

    { x: 2, y: 11, type:PLACEMENT_TYPE_CONVEYOR,direction:'LEFT'},
    { x: 3, y: 10, type:PLACEMENT_TYPE_CONVEYOR,direction:'UP'},
    { x: 3, y: 12, type:PLACEMENT_TYPE_CONVEYOR,direction:'DOWN'},
    { x: 4, y: 11, type:PLACEMENT_TYPE_CONVEYOR,direction:'RIGHT'},
    { x: 13, y: 7, type:PLACEMENT_TYPE_CONVEYOR,direction:'DOWN'},
    { x: 13, y: 8, type:PLACEMENT_TYPE_CONVEYOR,direction:'DOWN'},
    { x: 13, y: 9, type:PLACEMENT_TYPE_CONVEYOR,direction:'DOWN'},
    { x: 13, y: 10, type:PLACEMENT_TYPE_CONVEYOR,direction:'DOWN'},
    { x: 16, y: 5, type:PLACEMENT_TYPE_CONVEYOR,direction:'LEFT'},
    { x: 17, y: 5, type:PLACEMENT_TYPE_CONVEYOR,direction:'LEFT'},

    { x: 20, y: 2, type:PLACEMENT_TYPE_FIRE_PICKUP},
    { x: 13, y: 3, type:PLACEMENT_TYPE_FIRE},
    { x: 13, y: 5, type:PLACEMENT_TYPE_FIRE},
    { x: 13, y: 11, type:PLACEMENT_TYPE_FIRE},
    { x: 14, y: 4, type:PLACEMENT_TYPE_FIRE},

    { x: 17, y: 8, type:PLACEMENT_TYPE_SWITCH_DOOR,isRaised:true},
    { x: 15, y: 13, type:PLACEMENT_TYPE_SWITCH},

    { x: 16, y: 1, type:PLACEMENT_TYPE_WATER},
    { x: 16, y: 2, type:PLACEMENT_TYPE_WATER},
    { x: 16, y: 3, type:PLACEMENT_TYPE_WATER},
    { x: 16, y: 4, type:PLACEMENT_TYPE_WATER},
    { x: 16, y: 6, type:PLACEMENT_TYPE_WATER},
    { x: 16, y: 7, type:PLACEMENT_TYPE_WATER},
    { x: 17, y: 6, type:PLACEMENT_TYPE_WATER},
    { x: 17, y: 7, type:PLACEMENT_TYPE_WATER},
    { x: 17, y: 9, type:PLACEMENT_TYPE_WATER},
    { x: 17, y: 10, type:PLACEMENT_TYPE_WATER},
    { x: 18, y: 9, type:PLACEMENT_TYPE_WATER},
    { x: 18, y: 10, type:PLACEMENT_TYPE_WATER},
    { x: 18, y: 11, type:PLACEMENT_TYPE_WATER},

    { x: 18, y: 8, type:PLACEMENT_TYPE_ICE},
    { x: 19, y: 8, type:PLACEMENT_TYPE_ICE},
    { x: 19, y: 9, type:PLACEMENT_TYPE_ICE},
    { x: 20, y: 7, type:PLACEMENT_TYPE_ICE},
    { x: 20, y: 8, type:PLACEMENT_TYPE_ICE},
    { x: 20, y: 9, type:PLACEMENT_TYPE_ICE},

    { x: 5, y: 6, type:PLACEMENT_TYPE_ROAMING_ENEMY},
    { x: 6, y: 5, type:PLACEMENT_TYPE_ROAMING_ENEMY},
    { x: 6, y: 7, type:PLACEMENT_TYPE_ROAMING_ENEMY},
    { x: 7, y: 6, type:PLACEMENT_TYPE_ROAMING_ENEMY},

    { x: 13, y: 12, type:PLACEMENT_TYPE_FLYING_ENEMY},
    { x: 18, y: 1, type:PLACEMENT_TYPE_FLYING_ENEMY},

    { x: 17, y: 4, type:PLACEMENT_TYPE_GROUND_ENEMY},
    { x: 21, y: 6, type:PLACEMENT_TYPE_GROUND_ENEMY},

    { x: 12, y: 2, type:PLACEMENT_TYPE_THIEF},

  ],
};

export default DemoLevel6;
