import {
  LEVEL_THEMES,
  PLACEMENT_TYPE_FLOUR,
  PLACEMENT_TYPE_GOAL,
  PLACEMENT_TYPE_HERO,
  PLACEMENT_TYPE_WALL,
  PLACEMENT_TYPE_LOCK,
  PLACEMENT_TYPE_KEY,
  PLACEMENT_TYPE_WATER,
  PLACEMENT_TYPE_WATER_PICKUP,
  PLACEMENT_TYPE_GROUND_ENEMY,
  PLACEMENT_TYPE_FLYING_ENEMY,
  PLACEMENT_TYPE_ROAMING_ENEMY,
  PLACEMENT_TYPE_CONVEYOR,
  PLACEMENT_TYPE_ICE,
  PLACEMENT_TYPE_ICE_PICKUP,
  PLACEMENT_TYPE_FIRE,
  PLACEMENT_TYPE_FIRE_PICKUP,
  PLACEMENT_TYPE_SWITCH_DOOR,
  PLACEMENT_TYPE_SWITCH,
  PLACEMENT_TYPE_TELEPORT,
  PLACEMENT_TYPE_THIEF,
  PLACEMENT_TYPE_CIABATTA,
  PLACEMENT_TYPE_RABBIT,
  PLACEMENT_TYPE_PRINCESS,
  PLACEMENT_TYPE_BOARD,
} from "../helpers/consts";
const DemoLevel1 = {
  theme: LEVEL_THEMES.GRAY,
  tilesWidth: 46,
  tilesHeight: 3,
  placements: [
    { x: 2, y: 2, type: PLACEMENT_TYPE_HERO },
    // { x: 2, y: 5, type: PLACEMENT_TYPE_FLOUR },
    { x: 45, y: 2, type: PLACEMENT_TYPE_GOAL },

    { x: 9, y: 2, type: PLACEMENT_TYPE_WATER_PICKUP},
    { x: 10, y: 1, type: PLACEMENT_TYPE_WATER},
    { x: 10, y: 2, type: PLACEMENT_TYPE_WATER},
    { x: 10, y: 3, type: PLACEMENT_TYPE_WATER},
    { x: 11, y: 1, type: PLACEMENT_TYPE_WATER},
    { x: 11, y: 2, type: PLACEMENT_TYPE_WATER},
    { x: 11, y: 3, type: PLACEMENT_TYPE_WATER},
    { x: 12, y: 1, type: PLACEMENT_TYPE_WATER},
    { x: 12, y: 2, type: PLACEMENT_TYPE_WATER},
    { x: 12, y: 3, type: PLACEMENT_TYPE_WATER},

    { x: 15, y: 2, type: PLACEMENT_TYPE_ICE_PICKUP},
    { x: 16, y: 1, type: PLACEMENT_TYPE_ICE,corner:"TOP_LEFT"},
    { x: 16, y: 2, type: PLACEMENT_TYPE_ICE},
    { x: 16, y: 3, type: PLACEMENT_TYPE_ICE},
    { x: 17, y: 1, type: PLACEMENT_TYPE_ICE},
    { x: 17, y: 2, type: PLACEMENT_TYPE_ICE},
    { x: 17, y: 3, type: PLACEMENT_TYPE_ICE},
    { x: 18, y: 1, type: PLACEMENT_TYPE_ICE,corner:"TOP_RIGHT"},
    { x: 18, y: 2, type: PLACEMENT_TYPE_ICE},
    { x: 18, y: 3, type: PLACEMENT_TYPE_ICE,corner:"BOTTOM_RIGHT"},

    { x: 21, y: 2, type: PLACEMENT_TYPE_FIRE_PICKUP},
    { x: 22, y: 1, type: PLACEMENT_TYPE_FIRE},
    { x: 22, y: 2, type: PLACEMENT_TYPE_FIRE},
    { x: 22, y: 3, type: PLACEMENT_TYPE_FIRE},
    { x: 23, y: 1, type: PLACEMENT_TYPE_FIRE},
    { x: 23, y: 2, type: PLACEMENT_TYPE_FIRE},
    { x: 23, y: 3, type: PLACEMENT_TYPE_FIRE},
    { x: 24, y: 1, type: PLACEMENT_TYPE_FIRE},
    { x: 24, y: 2, type: PLACEMENT_TYPE_FIRE},
    { x: 24, y: 3, type: PLACEMENT_TYPE_FIRE},

    { x: 27, y: 2, type: PLACEMENT_TYPE_SWITCH },
    { x: 28, y: 1, type: PLACEMENT_TYPE_SWITCH_DOOR, isRaised: true },
    { x: 28, y: 2, type: PLACEMENT_TYPE_SWITCH_DOOR, isRaised: true },
    { x: 28, y: 3, type: PLACEMENT_TYPE_SWITCH_DOOR, isRaised: true },
    
    { x: 32, y: 2, type: PLACEMENT_TYPE_TELEPORT},
    { x: 34, y: 2, type: PLACEMENT_TYPE_TELEPORT},
    { x: 33, y: 1, type: PLACEMENT_TYPE_WALL},
    { x: 33, y: 2, type: PLACEMENT_TYPE_WALL},
    { x: 33, y: 3, type: PLACEMENT_TYPE_WALL},

    { x: 39, y: 1, type: PLACEMENT_TYPE_THIEF},
    { x: 39, y: 2, type: PLACEMENT_TYPE_THIEF},
    { x: 39, y: 3, type: PLACEMENT_TYPE_THIEF},

    { x: 41, y: 2, type: PLACEMENT_TYPE_KEY},
    { x: 43, y: 2, type: PLACEMENT_TYPE_LOCK},
    { x: 43, y: 1, type: PLACEMENT_TYPE_WALL},
    { x: 43, y: 3, type: PLACEMENT_TYPE_WALL},
    
    { x: 5, y: 2, type: PLACEMENT_TYPE_RABBIT,Talking:"你好~是后羿啊!嫦娥被抓走了!熟悉這些道具的作用然後拿上這個月亮寶石去拯救她吧!"},
    { x: 8, y: 2, type: PLACEMENT_TYPE_BOARD,Talking:"穿上這個可以在水裡游泳~"},
    { x: 14, y: 2, type: PLACEMENT_TYPE_BOARD,Talking:"穿上這個就不會滑了~"},
    { x: 20, y: 2, type: PLACEMENT_TYPE_BOARD,Talking:"穿上這個可以防火~"},
    { x: 26, y: 2, type: PLACEMENT_TYPE_BOARD,Talking:"踩下這個按鈕就會改變方塊的狀態~"},
    { x: 31, y: 2, type: PLACEMENT_TYPE_BOARD,Talking:"只要踩到這個方塊就會移動到另一個對應的方塊哦~"},
    { x: 37, y: 2, type: PLACEMENT_TYPE_BOARD,Talking:"踩到這個方塊就會還原之前拿到的道具，要小心哦~"},

   


  ],
};

export default DemoLevel1;
