import {
  LEVEL_THEMES,
  PLACEMENT_TYPE_FLOUR,
  PLACEMENT_TYPE_GOAL,
  PLACEMENT_TYPE_HERO,
  PLACEMENT_TYPE_WALL,
  PLACEMENT_TYPE_LOCK,
  PLACEMENT_TYPE_KEY,
  PLACEMENT_TYPE_WATER,
  PLACEMENT_TYPE_WATER_PICKUP,
  PLACEMENT_TYPE_GROUND_ENEMY,
  PLACEMENT_TYPE_FLYING_ENEMY,
  PLACEMENT_TYPE_ROAMING_ENEMY,
  PLACEMENT_TYPE_CONVEYOR,
  PLACEMENT_TYPE_ICE,
  PLACEMENT_TYPE_ICE_PICKUP,
  PLACEMENT_TYPE_FIRE,
  PLACEMENT_TYPE_FIRE_PICKUP,
  PLACEMENT_TYPE_SWITCH_DOOR,
  PLACEMENT_TYPE_SWITCH,
  PLACEMENT_TYPE_TELEPORT,
  PLACEMENT_TYPE_THIEF,
  PLACEMENT_TYPE_CIABATTA,
  PLACEMENT_TYPE_RABBIT,
  PLACEMENT_TYPE_PRINCESS,
} from "../helpers/consts";
const DemoLevel5 = {
  theme: LEVEL_THEMES.GRAY,
  tilesWidth: 19,
  tilesHeight: 9,
  placements: [
    { x: 1, y: 5, type: PLACEMENT_TYPE_HERO },
    { x: 15, y: 5, type: PLACEMENT_TYPE_GOAL },

    { x: 18, y: 8, type: PLACEMENT_TYPE_LOCK,color:'BLUE' },
    { x: 19, y: 2, type: PLACEMENT_TYPE_KEY,color:'BLUE' },
    { x: 3, y: 2, type: PLACEMENT_TYPE_LOCK,color:'GREEN' },
    { x: 8, y: 8, type: PLACEMENT_TYPE_KEY,color:'GREEN' },

    { x: 1, y: 1, type: PLACEMENT_TYPE_RABBIT,Talking:"月亮在天空中的位置會變，是因為地球在自轉哦！就像太陽東升西落一樣，月亮的位置也會慢慢改變，都是地球轉動的結果呢！",point:'地球在自轉'},
    { x: 7, y: 2, type: PLACEMENT_TYPE_RABBIT,Talking:"月亮跟太陽一樣，都是從東方升起，然後慢慢移動到天空，再從西方落下哦！",point:'從東方升起'},
    { x: 11, y: 9, type: PLACEMENT_TYPE_RABBIT,Talking:"當我們看到月亮又大又圓的時候，這叫做「滿月」哦！這時候的月亮最亮最美呢！",point:'滿月'},
    { x: 19, y: 9, type: PLACEMENT_TYPE_RABBIT,Talking:"當月亮變得像一條細細的弧線時，我們叫它「新月」哦！這時候的月亮特別害羞，只露出一點點光亮呢！",point:'新月'},

    { x: 3, y: 1, type:PLACEMENT_TYPE_WALL},
    { x: 6, y: 5, type:PLACEMENT_TYPE_WALL},
    { x: 7, y: 5, type:PLACEMENT_TYPE_WALL},
    { x: 8, y: 5, type:PLACEMENT_TYPE_WALL},
    { x: 9, y: 5, type:PLACEMENT_TYPE_WALL},
    { x: 10, y: 1, type:PLACEMENT_TYPE_WALL},
    { x: 10, y: 2, type:PLACEMENT_TYPE_WALL},
    { x: 10, y: 3, type:PLACEMENT_TYPE_WALL},
    { x: 10, y: 4, type:PLACEMENT_TYPE_WALL},
    { x: 10, y: 5, type:PLACEMENT_TYPE_WALL},
    { x: 10, y: 7, type:PLACEMENT_TYPE_WALL},
    { x: 10, y: 8, type:PLACEMENT_TYPE_WALL},
    { x: 10, y: 9, type:PLACEMENT_TYPE_WALL},
    { x: 17, y: 7, type:PLACEMENT_TYPE_WALL},
    { x: 17, y: 9, type:PLACEMENT_TYPE_WALL},
    { x: 19, y: 7, type:PLACEMENT_TYPE_WALL},
    { x: 19, y: 8, type:PLACEMENT_TYPE_WALL},

    { x: 3, y: 9, type:PLACEMENT_TYPE_ICE_PICKUP},
    { x: 12, y: 8, type:PLACEMENT_TYPE_ICE_PICKUP},
    { x: 6, y: 1, type:PLACEMENT_TYPE_ICE,corner:"TOP_LEFT"},
    { x: 6, y: 2, type:PLACEMENT_TYPE_ICE},
    { x: 6, y: 3, type:PLACEMENT_TYPE_ICE},
    { x: 6, y: 4, type:PLACEMENT_TYPE_ICE},
    { x: 7, y: 1, type:PLACEMENT_TYPE_ICE},
    { x: 7, y: 2, type:PLACEMENT_TYPE_ICE},
    { x: 7, y: 3, type:PLACEMENT_TYPE_ICE},
    { x: 7, y: 4, type:PLACEMENT_TYPE_ICE},
    { x: 8, y: 1, type:PLACEMENT_TYPE_ICE},
    { x: 8, y: 2, type:PLACEMENT_TYPE_ICE},
    { x: 8, y: 3, type:PLACEMENT_TYPE_ICE},
    { x: 8, y: 4, type:PLACEMENT_TYPE_ICE},
    { x: 9, y: 1, type:PLACEMENT_TYPE_ICE,corner:'TOP_RIGHT'},
    { x: 9, y: 2, type:PLACEMENT_TYPE_ICE},
    { x: 9, y: 3, type:PLACEMENT_TYPE_ICE},
    { x: 9, y: 4, type:PLACEMENT_TYPE_ICE,corner:'BOTTOM_RIGHT'},

    { x: 11, y: 4, type:PLACEMENT_TYPE_ICE},
    { x: 11, y: 5, type:PLACEMENT_TYPE_ICE},
    { x: 11, y: 6, type:PLACEMENT_TYPE_ICE,corner:'BOTTOM_LEFT'},
    { x: 12, y: 4, type:PLACEMENT_TYPE_ICE},
    { x: 12, y: 5, type:PLACEMENT_TYPE_ICE},
    { x: 12, y: 6, type:PLACEMENT_TYPE_ICE},
    { x: 13, y: 4, type:PLACEMENT_TYPE_ICE},
    { x: 13, y: 5, type:PLACEMENT_TYPE_ICE},
    { x: 13, y: 6, type:PLACEMENT_TYPE_ICE},

    { x: 14, y: 1, type:PLACEMENT_TYPE_ICE},
    { x: 14, y: 2, type:PLACEMENT_TYPE_ICE},
    { x: 14, y: 3, type:PLACEMENT_TYPE_ICE},
    { x: 15, y: 1, type:PLACEMENT_TYPE_ICE},
    { x: 15, y: 2, type:PLACEMENT_TYPE_ICE},
    { x: 15, y: 3, type:PLACEMENT_TYPE_ICE},
    { x: 16, y: 1, type:PLACEMENT_TYPE_ICE},
    { x: 16, y: 2, type:PLACEMENT_TYPE_ICE},
    { x: 16, y: 3, type:PLACEMENT_TYPE_ICE},

    { x: 18, y: 4, type:PLACEMENT_TYPE_ICE},
    { x: 18, y: 5, type:PLACEMENT_TYPE_ICE},
    { x: 18, y: 6, type:PLACEMENT_TYPE_ICE},
    { x: 19, y: 4, type:PLACEMENT_TYPE_ICE},
    { x: 19, y: 5, type:PLACEMENT_TYPE_ICE},
    { x: 19, y: 6, type:PLACEMENT_TYPE_ICE},

    { x: 8, y: 3, type:PLACEMENT_TYPE_FIRE_PICKUP},
    { x: 7, y: 7, type:PLACEMENT_TYPE_FIRE},
    { x: 7, y: 8, type:PLACEMENT_TYPE_FIRE},
    { x: 7, y: 9, type:PLACEMENT_TYPE_FIRE},
    { x: 8, y: 7, type:PLACEMENT_TYPE_FIRE},
    { x: 8, y: 8, type:PLACEMENT_TYPE_FIRE},
    { x: 8, y: 9, type:PLACEMENT_TYPE_FIRE},
    { x: 9, y: 7, type:PLACEMENT_TYPE_FIRE},
    { x: 9, y: 8, type:PLACEMENT_TYPE_FIRE},
    { x: 9, y: 9, type:PLACEMENT_TYPE_FIRE},

    { x: 19, y: 6, type:PLACEMENT_TYPE_WATER_PICKUP},
    { x: 14, y: 4, type:PLACEMENT_TYPE_WATER},
    { x: 14, y: 5, type:PLACEMENT_TYPE_WATER},
    { x: 14, y: 6, type:PLACEMENT_TYPE_WATER},
    { x: 14, y: 8, type:PLACEMENT_TYPE_WATER},
    { x: 14, y: 9, type:PLACEMENT_TYPE_WATER},
    { x: 15, y: 4, type:PLACEMENT_TYPE_WATER},
    { x: 15, y: 6, type:PLACEMENT_TYPE_WATER},
    { x: 15, y: 8, type:PLACEMENT_TYPE_WATER},
    { x: 15, y: 9, type:PLACEMENT_TYPE_WATER},
    { x: 16, y: 4, type:PLACEMENT_TYPE_WATER},
    { x: 16, y: 5, type:PLACEMENT_TYPE_WATER},
    { x: 16, y: 6, type:PLACEMENT_TYPE_WATER},
    { x: 16, y: 8, type:PLACEMENT_TYPE_WATER},
    { x: 16, y: 9, type:PLACEMENT_TYPE_WATER},

    { x: 10, y: 6, type:PLACEMENT_TYPE_TELEPORT},
    { x: 12, y: 2, type:PLACEMENT_TYPE_TELEPORT},

    { x: 9, y: 6, type:PLACEMENT_TYPE_THIEF},
    { x: 17, y: 1, type:PLACEMENT_TYPE_THIEF},
    { x: 17, y: 2, type:PLACEMENT_TYPE_THIEF},
    { x: 17, y: 3, type:PLACEMENT_TYPE_THIEF},

    { x: 1, y: 3, type:PLACEMENT_TYPE_SWITCH_DOOR,isRaised:false},
    { x: 1, y: 4, type:PLACEMENT_TYPE_SWITCH_DOOR,isRaised:true},
    { x: 1, y: 6, type:PLACEMENT_TYPE_SWITCH_DOOR,isRaised:false},
    { x: 1, y: 7, type:PLACEMENT_TYPE_SWITCH_DOOR,isRaised:true},
    { x: 2, y: 3, type:PLACEMENT_TYPE_SWITCH_DOOR,isRaised:false},
    { x: 2, y: 4, type:PLACEMENT_TYPE_SWITCH_DOOR,isRaised:true},
    { x: 2, y: 6, type:PLACEMENT_TYPE_SWITCH_DOOR,isRaised:false},
    { x: 2, y: 7, type:PLACEMENT_TYPE_SWITCH_DOOR,isRaised:true},
    { x: 3, y: 3, type:PLACEMENT_TYPE_SWITCH_DOOR,isRaised:false},
    { x: 3, y: 4, type:PLACEMENT_TYPE_SWITCH_DOOR,isRaised:true},
    { x: 3, y: 6, type:PLACEMENT_TYPE_SWITCH_DOOR,isRaised:false},
    { x: 3, y: 7, type:PLACEMENT_TYPE_SWITCH_DOOR,isRaised:true},
    { x: 4, y: 3, type:PLACEMENT_TYPE_SWITCH_DOOR,isRaised:false},
    { x: 4, y: 4, type:PLACEMENT_TYPE_SWITCH_DOOR,isRaised:true},
    { x: 4, y: 6, type:PLACEMENT_TYPE_SWITCH_DOOR,isRaised:false},
    { x: 4, y: 7, type:PLACEMENT_TYPE_SWITCH_DOOR,isRaised:true},
    { x: 5, y: 3, type:PLACEMENT_TYPE_SWITCH_DOOR,isRaised:false},
    { x: 5, y: 4, type:PLACEMENT_TYPE_SWITCH_DOOR,isRaised:true},
    { x: 5, y: 6, type:PLACEMENT_TYPE_SWITCH_DOOR,isRaised:false},
    { x: 5, y: 7, type:PLACEMENT_TYPE_SWITCH_DOOR,isRaised:true},
    { x: 5, y: 8, type:PLACEMENT_TYPE_SWITCH_DOOR,isRaised:false},
    { x: 5, y: 9, type:PLACEMENT_TYPE_SWITCH_DOOR,isRaised:false},
    { x: 11, y: 7, type:PLACEMENT_TYPE_SWITCH_DOOR,isRaised:true},
    { x: 12, y: 7, type:PLACEMENT_TYPE_SWITCH_DOOR,isRaised:true},
    { x: 13, y: 7, type:PLACEMENT_TYPE_SWITCH_DOOR,isRaised:true},
    { x: 13, y: 8, type:PLACEMENT_TYPE_SWITCH_DOOR,isRaised:true},
    { x: 13, y: 9, type:PLACEMENT_TYPE_SWITCH_DOOR,isRaised:true},

    { x: 4, y: 5, type:PLACEMENT_TYPE_SWITCH},
    { x: 18, y: 9, type:PLACEMENT_TYPE_SWITCH},

    { x: 14, y: 7, type:PLACEMENT_TYPE_CONVEYOR,direction:'DOWN'},
    { x: 15, y: 7, type:PLACEMENT_TYPE_CONVEYOR,direction:'DOWN'},
    { x: 16, y: 7, type:PLACEMENT_TYPE_CONVEYOR,direction:'DOWN'},
    { x: 17, y: 4, type:PLACEMENT_TYPE_CONVEYOR,direction:'RIGHT'},
    { x: 17, y: 5, type:PLACEMENT_TYPE_CONVEYOR,direction:'RIGHT'},
    { x: 17, y: 6, type:PLACEMENT_TYPE_CONVEYOR,direction:'RIGHT'},

    { x: 3, y: 8, type:PLACEMENT_TYPE_ROAMING_ENEMY},

    



  ],
};

export default DemoLevel5;
