import {
  LEVEL_THEMES,
  PLACEMENT_TYPE_FLOUR,
  PLACEMENT_TYPE_GOAL,
  PLACEMENT_TYPE_HERO,
  PLACEMENT_TYPE_WALL,
  PLACEMENT_TYPE_LOCK,
  PLACEMENT_TYPE_KEY,
  PLACEMENT_TYPE_WATER,
  PLACEMENT_TYPE_WATER_PICKUP,
  PLACEMENT_TYPE_GROUND_ENEMY,
  PLACEMENT_TYPE_FLYING_ENEMY,
  PLACEMENT_TYPE_ROAMING_ENEMY,
  PLACEMENT_TYPE_CONVEYOR,
  PLACEMENT_TYPE_ICE,
  PLACEMENT_TYPE_ICE_PICKUP,
  PLACEMENT_TYPE_FIRE,
  PLACEMENT_TYPE_FIRE_PICKUP,
  PLACEMENT_TYPE_SWITCH_DOOR,
  PLACEMENT_TYPE_SWITCH,
  PLACEMENT_TYPE_TELEPORT,
  PLACEMENT_TYPE_THIEF,
  PLACEMENT_TYPE_CIABATTA,
  PLACEMENT_TYPE_RABBIT,
} from "../helpers/consts";
const DemoLevel8 = {
  theme: LEVEL_THEMES.GRAY,
  tilesWidth: 13,
  tilesHeight: 13,
  placements: [
    { x: 7, y: 7, type: PLACEMENT_TYPE_HERO },
    { x: 12, y: 2, type: PLACEMENT_TYPE_GOAL },

    { x: 11, y: 2, type: PLACEMENT_TYPE_LOCK },
    { x: 6, y: 5, type: PLACEMENT_TYPE_KEY },

    { 
      x: 2, y: 4, type: PLACEMENT_TYPE_RABBIT,
      Talking: "月亮的自轉和公轉週期一樣長，這就是為什麼我們永遠只看到月亮的同一面，這種現象叫作潮汐鎖定哦！", 
      point: "潮汐鎖定" 
    },
    { 
      x: 5, y: 2, type: PLACEMENT_TYPE_RABBIT,
      Talking: "你知道嗎？雖然每個月都有新月，但不一定都會有日蝕，因為月亮的軌道有一個傾斜角度，不是每次都在同一平面上！", 
      point: "傾斜角度" 
    },
    { 
      x: 10, y: 12, type: PLACEMENT_TYPE_RABBIT,
      Talking: "上弦月出現時，太陽、地球和月亮大約形成 90 度的角度，這時你會看到一半亮亮的月亮哦～", 
      point: "90 度的角度" 
    },
    { 
      x: 11, y: 1, type: PLACEMENT_TYPE_RABBIT,
      Talking: "在滿月和新月的時候，太陽和月亮的引力方向一致，所以會產生超大的潮汐，這叫作大潮！", 
      point: "大潮" 
    },
    

    { x: 3, y: 13, type:PLACEMENT_TYPE_WALL},
    { x: 4, y: 6, type:PLACEMENT_TYPE_WALL},
    { x: 4, y: 12, type:PLACEMENT_TYPE_WALL},
    { x: 8, y: 3, type:PLACEMENT_TYPE_WALL},
    { x: 9, y: 5, type:PLACEMENT_TYPE_WALL},
    { x: 9, y: 10, type:PLACEMENT_TYPE_WALL},
    { x: 13, y: 6, type:PLACEMENT_TYPE_WALL},
    { x: 13, y: 11, type:PLACEMENT_TYPE_WALL},

    { x: 1, y: 6, type:PLACEMENT_TYPE_WATER},
    { x: 3, y: 1, type:PLACEMENT_TYPE_WATER},
    { x: 3, y: 11, type:PLACEMENT_TYPE_WATER},
    { x: 4, y: 7, type:PLACEMENT_TYPE_WATER},
    { x: 4, y: 13, type:PLACEMENT_TYPE_WATER},
    { x: 5, y: 13, type:PLACEMENT_TYPE_WATER},
    { x: 6, y: 2, type:PLACEMENT_TYPE_WATER},
    { x: 6, y: 10, type:PLACEMENT_TYPE_WATER},
    { x: 8, y: 12, type:PLACEMENT_TYPE_WATER},
    { x: 9, y: 3, type:PLACEMENT_TYPE_WATER},
    { x: 10, y: 9, type:PLACEMENT_TYPE_WATER},
    { x: 12, y: 1, type:PLACEMENT_TYPE_WATER},
    { x: 12, y: 11, type:PLACEMENT_TYPE_WATER},
    { x: 13, y: 7, type:PLACEMENT_TYPE_WATER},

    { x: 1, y: 1, type:PLACEMENT_TYPE_ICE,corner:"TOP_LEFT"},
    { x: 1, y: 2, type:PLACEMENT_TYPE_ICE},
    { x: 1, y: 3, type:PLACEMENT_TYPE_ICE},
    { x: 1, y: 4, type:PLACEMENT_TYPE_ICE},
    { x: 1, y: 5, type:PLACEMENT_TYPE_ICE},
    { x: 1, y: 7, type:PLACEMENT_TYPE_ICE},
    { x: 1, y: 8, type:PLACEMENT_TYPE_ICE},
    { x: 1, y: 9, type:PLACEMENT_TYPE_ICE},
    { x: 1, y: 10, type:PLACEMENT_TYPE_ICE},
    { x: 1, y: 11, type:PLACEMENT_TYPE_ICE},
    { x: 1, y: 12, type:PLACEMENT_TYPE_ICE},
    { x: 1, y: 13, type:PLACEMENT_TYPE_ICE,corner:"BOTTOM_LEFT"},

    { x: 2, y: 1, type:PLACEMENT_TYPE_ICE},
    { x: 2, y: 2, type:PLACEMENT_TYPE_ICE},
    { x: 2, y: 3, type:PLACEMENT_TYPE_ICE},
    { x: 2, y: 5, type:PLACEMENT_TYPE_ICE},
    { x: 2, y: 6, type:PLACEMENT_TYPE_ICE},
    { x: 2, y: 7, type:PLACEMENT_TYPE_ICE},
    { x: 2, y: 8, type:PLACEMENT_TYPE_ICE},
    { x: 2, y: 9, type:PLACEMENT_TYPE_ICE},
    { x: 2, y: 10, type:PLACEMENT_TYPE_ICE},
    { x: 2, y: 11, type:PLACEMENT_TYPE_ICE},
    { x: 2, y: 12, type:PLACEMENT_TYPE_ICE},
    { x: 2, y: 13, type:PLACEMENT_TYPE_ICE},

    { x: 3, y: 2, type:PLACEMENT_TYPE_ICE},
    { x: 3, y: 3, type:PLACEMENT_TYPE_ICE},
    { x: 3, y: 4, type:PLACEMENT_TYPE_ICE},
    { x: 3, y: 5, type:PLACEMENT_TYPE_ICE},
    { x: 3, y: 6, type:PLACEMENT_TYPE_ICE},
    { x: 3, y: 7, type:PLACEMENT_TYPE_ICE},
    { x: 3, y: 8, type:PLACEMENT_TYPE_ICE},
    { x: 3, y: 9, type:PLACEMENT_TYPE_ICE},
    { x: 3, y: 10, type:PLACEMENT_TYPE_ICE},
    { x: 3, y: 12, type:PLACEMENT_TYPE_ICE},

    { x: 4, y: 1, type:PLACEMENT_TYPE_ICE},
    { x: 4, y: 2, type:PLACEMENT_TYPE_ICE},
    { x: 4, y: 3, type:PLACEMENT_TYPE_ICE},
    { x: 4, y: 4, type:PLACEMENT_TYPE_ICE},
    { x: 4, y: 5, type:PLACEMENT_TYPE_ICE},
    { x: 4, y: 8, type:PLACEMENT_TYPE_ICE},
    { x: 4, y: 9, type:PLACEMENT_TYPE_ICE},
    { x: 4, y: 10, type:PLACEMENT_TYPE_ICE},
    { x: 4, y: 11, type:PLACEMENT_TYPE_ICE},


    { x: 5, y: 1, type:PLACEMENT_TYPE_ICE},
    { x: 5, y: 3, type:PLACEMENT_TYPE_ICE},
    { x: 5, y: 4, type:PLACEMENT_TYPE_ICE},
    { x: 5, y: 5, type:PLACEMENT_TYPE_ICE},
    { x: 5, y: 6, type:PLACEMENT_TYPE_ICE},
    { x: 5, y: 7, type:PLACEMENT_TYPE_ICE},
    { x: 5, y: 8, type:PLACEMENT_TYPE_ICE},
    { x: 5, y: 9, type:PLACEMENT_TYPE_ICE},
    { x: 5, y: 10, type:PLACEMENT_TYPE_ICE},
    { x: 5, y: 11, type:PLACEMENT_TYPE_ICE},
    { x: 5, y: 12, type:PLACEMENT_TYPE_ICE},
  

    { x: 6, y: 1, type:PLACEMENT_TYPE_ICE},
    { x: 6, y: 3, type:PLACEMENT_TYPE_ICE},
    { x: 6, y: 4, type:PLACEMENT_TYPE_ICE},
    { x: 6, y: 5, type:PLACEMENT_TYPE_ICE},
    { x: 6, y: 9, type:PLACEMENT_TYPE_ICE},
    { x: 6, y: 11, type:PLACEMENT_TYPE_ICE},
    { x: 6, y: 12, type:PLACEMENT_TYPE_ICE},
    { x: 6, y: 13, type:PLACEMENT_TYPE_ICE},

    { x: 7, y: 1, type:PLACEMENT_TYPE_ICE},
    { x: 7, y: 2, type:PLACEMENT_TYPE_ICE},
    { x: 7, y: 3, type:PLACEMENT_TYPE_ICE},
    { x: 7, y: 4, type:PLACEMENT_TYPE_ICE},
    { x: 7, y: 5, type:PLACEMENT_TYPE_ICE},
    { x: 7, y: 9, type:PLACEMENT_TYPE_ICE},
    { x: 7, y: 10, type:PLACEMENT_TYPE_ICE},
    { x: 7, y: 11, type:PLACEMENT_TYPE_ICE},
    { x: 7, y: 12, type:PLACEMENT_TYPE_ICE},
    { x: 7, y: 13, type:PLACEMENT_TYPE_ICE},

    { x: 8, y: 1, type:PLACEMENT_TYPE_ICE},
    { x: 8, y: 2, type:PLACEMENT_TYPE_ICE},
    { x: 8, y: 4, type:PLACEMENT_TYPE_ICE},
    { x: 8, y: 5, type:PLACEMENT_TYPE_ICE},
    { x: 8, y: 9, type:PLACEMENT_TYPE_ICE},
    { x: 8, y: 10, type:PLACEMENT_TYPE_ICE},
    { x: 8, y: 11, type:PLACEMENT_TYPE_ICE},
    { x: 8, y: 13, type:PLACEMENT_TYPE_ICE},

    { x: 9, y: 1, type:PLACEMENT_TYPE_ICE},
    { x: 9, y: 2, type:PLACEMENT_TYPE_ICE},
    { x: 9, y: 4, type:PLACEMENT_TYPE_ICE},
    { x: 9, y: 6, type:PLACEMENT_TYPE_ICE},
    { x: 9, y: 7, type:PLACEMENT_TYPE_ICE},
    { x: 9, y: 8, type:PLACEMENT_TYPE_ICE},
    { x: 9, y: 9, type:PLACEMENT_TYPE_ICE},
    { x: 9, y: 11, type:PLACEMENT_TYPE_ICE},
    { x: 9, y: 12, type:PLACEMENT_TYPE_ICE},
    { x: 9, y: 13, type:PLACEMENT_TYPE_ICE},

    { x: 10, y: 1, type:PLACEMENT_TYPE_ICE},
    { x: 10, y: 2, type:PLACEMENT_TYPE_ICE},
    { x: 10, y: 3, type:PLACEMENT_TYPE_ICE},
    { x: 10, y: 4, type:PLACEMENT_TYPE_ICE},
    { x: 10, y: 5, type:PLACEMENT_TYPE_ICE},
    { x: 10, y: 6, type:PLACEMENT_TYPE_ICE},
    { x: 10, y: 7, type:PLACEMENT_TYPE_ICE},
    { x: 10, y: 8, type:PLACEMENT_TYPE_ICE},
    { x: 10, y: 10, type:PLACEMENT_TYPE_ICE},
    { x: 10, y: 11, type:PLACEMENT_TYPE_ICE},
    { x: 10, y: 13, type:PLACEMENT_TYPE_ICE},

    { x: 11, y: 3, type:PLACEMENT_TYPE_ICE},
    { x: 11, y: 4, type:PLACEMENT_TYPE_ICE},
    { x: 11, y: 5, type:PLACEMENT_TYPE_ICE},
    { x: 11, y: 6, type:PLACEMENT_TYPE_ICE},
    { x: 11, y: 7, type:PLACEMENT_TYPE_ICE},
    { x: 11, y: 8, type:PLACEMENT_TYPE_ICE},
    { x: 11, y: 9, type:PLACEMENT_TYPE_ICE},
    { x: 11, y: 10, type:PLACEMENT_TYPE_ICE},
    { x: 11, y: 11, type:PLACEMENT_TYPE_ICE},
    { x: 11, y: 12, type:PLACEMENT_TYPE_ICE},
    { x: 11, y: 13, type:PLACEMENT_TYPE_ICE},

    { x: 12, y: 3, type:PLACEMENT_TYPE_ICE},
    { x: 12, y: 4, type:PLACEMENT_TYPE_ICE},
    { x: 12, y: 5, type:PLACEMENT_TYPE_ICE},
    { x: 12, y: 6, type:PLACEMENT_TYPE_ICE},
    { x: 12, y: 7, type:PLACEMENT_TYPE_ICE},
    { x: 12, y: 8, type:PLACEMENT_TYPE_ICE},
    { x: 12, y: 9, type:PLACEMENT_TYPE_ICE},
    { x: 12, y: 10, type:PLACEMENT_TYPE_ICE},
    { x: 12, y: 12, type:PLACEMENT_TYPE_ICE},
    { x: 12, y: 13, type:PLACEMENT_TYPE_ICE},

    { x: 13, y: 1, type:PLACEMENT_TYPE_ICE,corner:"TOP_RIGHT"},
    { x: 13, y: 2, type:PLACEMENT_TYPE_ICE},
    { x: 13, y: 3, type:PLACEMENT_TYPE_ICE},
    { x: 13, y: 4, type:PLACEMENT_TYPE_ICE},
    { x: 13, y: 5, type:PLACEMENT_TYPE_ICE},
    { x: 13, y: 8, type:PLACEMENT_TYPE_ICE},
    { x: 13, y: 9, type:PLACEMENT_TYPE_ICE},
    { x: 13, y: 10, type:PLACEMENT_TYPE_ICE},
    { x: 13, y: 12, type:PLACEMENT_TYPE_ICE},
    { x: 13, y: 13, type:PLACEMENT_TYPE_ICE,corner:"BOTTOM_RIGHT"},

  ],
};

export default DemoLevel8;
